### ISSUE TITLE
Empty space in the Samples input file causes an error message

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#100]
This is something that can be fixed manually, but Ivo suggested adding a check to remove it. Whenever I leave an empty space before or after a phenotype descriptor (see attached figure), the platform complains that there are no samples for a given phenotype.

I guess this could be solved informatically by removing empty spaces before/after the phenotype description.

![image](https://user-images.githubusercontent.com/85561624/160421587-0ef25d99-cda6-43a5-9639-1ec9d036baa9.png)

**Comment by stefanreifenberg** [comment]
We could simply trim whitespaces in the upload process. I can look into this once I am done with the current issues.

**Comment by AxelBigOmics** [comment]
Sounds good. Thanks for the prompt reply, Stefan!

**Comment by stefanreifenberg** [comment]
Could you please provide me an example file with the whitespace error to reproduce the issue

**Comment by AxelBigOmics** [comment]
Sure thing. Here are the original red counts file and the samples file with the spaces.

[counts.csv](https://github.com/bigomics/omicsplayground/files/8371696/counts.csv)
[samples_error.csv](https://github.com/bigomics/omicsplayground/files/8371702/samples_error.csv)

**Comment by stefanreifenberg** [comment]
I used these files and did not get an error so far. What do I have to do to reproduce the error described above?
![Screenshot 2022-03-29 at 15 40 27](https://user-images.githubusercontent.com/15939539/160624660-c93e7b6c-f320-415e-b01b-7ef2f186fad2.png)

**Comment by AxelBigOmics** [comment]
You should try to create pairwise comparisons using the "Contrasts" tab with either the "Gender" or "Disease" phenotypes. That is where an error shows up.

**Comment by stefanreifenberg** [comment]
Ok, can you also please send me the contrasts.csv file?

**Comment by AxelBigOmics** [comment]
I would, except I normally generate it through the platform and because of the error message, I cannot create a contrast.csv file with the platform. I've included the actual error message below.

![image](https://user-images.githubusercontent.com/85561624/160644257-0e8042bb-fa5e-4e7c-806b-c46c8af2007f.png)

**Comment by ivokwee** [comment]
@stefanreifenberg is this done? As you said, after loading CSV we can use trimws().
