### ISSUE TITLE
Sample clustering heatmap doesn't cluster samples

### ISSUE THREAD

**Issue by sooheon** [bigomics/omicsplayground#1003]
Can replicate with `example-data` on `v3.3.4-master240424`

By default, clusters 1-3 are assinged as follows:
![clustersamples-splitmap-pltmod-2](https://github.com/user-attachments/assets/49dca652-e71c-4718-b5b8-88134b8f8fd4)

If you download files (counts.csv, samples.csv...), remove cluster column from samples.csv and reupload, samples have only a single cluster:
![clustersamples-splitmap-pltmod-3](https://github.com/user-attachments/assets/b6324570-a3e7-4946-b958-e31026371b0d)

**Comment by mauromiguelm** [comment]
Hi @sooheon,

thanks for the bug report, I re-computed the dataset with example-data and I could get the same three clusters as in the figure below, in version `Omics Playground v3.5.0-beta5.9002+master240812`.

Could you kindly confirm that the counts you inputed are not quantile/logCPM normalized, and send me the data and settings you used for computation?

the raw counts should look like this:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mauro/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mauro/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">


</head>

<body link="#467886" vlink="#96607D">


  | notact_004 | notact_007 | notact_008 | notact_009
-- | -- | -- | -- | --
A1BG | 37.45 | 100.53 | 47.67 | 132.18
A2M | 1462.72 | 1325.35 | 1426.38 | 1733.85
AAAS | 16.94 | 47.4 | 15.94 | 50.86
AACS | 3.29 | 6.77 | 3.81 | 8.86
AAGAB | 0 | 0 | 0 | 0
AAK1 | 575.16 | 861.75 | 628.46 | 765.42
AAMDC | 5.85 | 24.83 | 11.55 | 11.11
AAMP | 48.13 | 28.85 | 102.59 | 54.29
AAR2 | 30.9 | 22.33 | 18.22 | 7.85



</body>

</html>






<img width="455" alt="image" src="https://github.com/user-attachments/assets/c3c88999-4dc3-47dd-b24f-c0de94818690">

<img width="404" alt="image" src="https://github.com/user-attachments/assets/bfc59ffe-11f5-41d7-b3e0-5400bc044e06">

**Comment by sooheon** [comment]
Yeah using same version, same raw counts / samples / contrasts as downloaded from example-data. Reanalyzed as proteomics dataset with no normalization and CPM + QN, and as RNAseq dataset as well. All seem to give me 1 cluster.

You can see single cluster here:

<img width="337" alt="image" src="https://github.com/user-attachments/assets/11ad0223-9469-41da-b389-51631339a642">

uploading PGX:

[rerun_example_data_for_clustering (1).pgx.zip](https://github.com/user-attachments/files/16594233/rerun_example_data_for_clustering.1.pgx.zip)

**Comment by mauromiguelm** [comment]
I can confirm v3.3.4 only assigned one cluster to the samples. Thanks a lot for the bug report, I will assign an issue internally and consider deprecating this version or issue a warning.

**Comment by sooheon** [comment]
BTW I ran the analysis with `Omics Playground v3.5.0-beta5.9002+master240812` and only got 1 cluster as well

**Comment by ivokwee** [comment]
Thanks. I think it will be fixed in this PR  https://github.com/bigomics/playbase/pull/134
