### ISSUE TITLE
WGCNA cannot be computed second time

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#1050]
Ken reported that WGCNA cannot be computed a second time and he has to restart the platform to do that. Please try to replicate this and confirm.

**Comment by ESCRI11** [comment]
@ivokwee can't reproduce on master, can you ask him to test on beta? Or is this feedback from beta?

**Comment by ivokwee** [comment]
They are using stable. So perhaps it is resolved in master&beta.
