### ISSUE TITLE
Volcano plot: add publication-ready base version as a card item

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#1056]
the plotly volcano does not have ggrepel, making it difficult to produce publication-ready volcano plot.

We should implement a base or ggplot that is publication-ready using a similar solution as clustering/heatmap (two plots in a card, plotly and base)

**Comment by mauromiguelm** [comment]
I used it before, its nice, but we have this already implemented volcano: https://github.com/bigomics/playbase/blob/239654ada63c9e8ca3ab9ec37b45f471a55a026a/R/pgx-plotting.R#L968-L1037 which might be already optimized for OPG

**Comment by ESCRI11** [comment]
It needs quite some work to get the coloring up to speed (up/down regulated ; grey out selected genes below thresholds) but it can work

**Comment by ESCRI11** [comment]
OPG and playbase branches containing the work-in-progress: [dev-static-volcanos](https://github.com/bigomics/omicsplayground/tree/dev-static-volcanos), [dev-static-volcanos](https://github.com/bigomics/playbase/tree/dev-static-volcanos)
