### ISSUE TITLE
GMT files not working in BETA (Omics Playground v3.5.0-beta10+master240902)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#1076]
I cannot get the GMT files to show up in the analysis in the test BETA version of the platform. The same GMT file works absolutely fine with the same dataset in the live version.

I'm adding the GMT files and the input datasets for anyone who's gonna work on it.

[GSE179195.zip](https://github.com/user-attachments/files/16873941/GSE179195.zip)

[Mouse.MitoCarta3.0.csv](https://github.com/user-attachments/files/16873929/Mouse.MitoCarta3.0.csv)

**Comment by ESCRI11** [comment]
Merging https://github.com/bigomics/playbase/pull/140 actually solves this issue

**Comment by ivokwee** [comment]
@mauromiguelm can you check and confirm solution?

**Comment by mauromiguelm** [comment]
fixed in https://github.com/bigomics/playbase/pull/140
