### ISSUE TITLE
plotly Error (?) using latest changes -- program freezes

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#11]
[17.05.2021 from Premsubr in googlegroups]

Hi,

After using the latest changes from GitHub (listed from 7-8 days or so ago) , using the source code version of omicsplayground the program freezes after displaying all the splash screen and just at the data up,oad window -- the window becomes gray and takes no inputs

Error in R is as follows:

```
DBG [BiomarkerBoard:<input_pdx_select>]  reacted
Warning: Error in if: argument is of length zero
  113: <reactive:corrected_counts> [modules/UploadModule.R#247]
   97: countsRT
   96: renderUI [modules/MakeContrastModule.R#89]
   95: func
   82: renderFunc
   81: output$load-upload_panel-makecontrast-UI
    1: shiny::runApp
[checkTables] called
[checkTables] 1 :
[checkTables] 2 :
[checkTables] 3 :
[checkTables] 5 :
[checkTables] 10 :
[ComputePgxServer:@enable] enabling compute button
DBG [LoadingBoard::inputData] ---------- reacted ---------------
DBG [LoadingBoard::inputData] AUTHENTICATION= none 
DBG [LoadingBoard::inputData] auth$logged= FALSE 
Warning in mapply(children, flex, FUN = function(el, flexValue) { :
  longer argument not a multiple of length of shorter
Warning: The 'plotly_restyle' event tied a source ID of 'pcoords' is not registered. In order to obtain this event data, please add `event_register(p, 'plotly_restyle')` to the plot (`p`) that you wish to obtain event data from.
DBG [BiomarkerBoard:<input_pdx_select>]  reacted
Warning: Error in <observer>: object 'COLLECTIONS' not found
  44: <observer> [boards/ClusteringBoard.R#1405]
   1: shiny::runApp
Warning in mapply(children, flex, FUN = function(el, flexValue) { :
  longer argument not a multiple of length of shorter

```

**Comment by c2b2pss** [comment]
PS: This affects the latest Docker pull also, at least for me. The program freezes at the results display, after finishing the compute portion.

**Comment by ivokwee** [comment]
Hi c2b2pss.  I tried the latest docker but cannot replicate your error using the example data. It may be some error in your data files. Can you please do the following?

1) What version are you using?
2) Can you try the example data? Does that work?
3) If you try your own data, try selecting only limma.trend and fisher, and deselect all 'extra analysis'. Does that work? 
4) Otherwise please can you send us your CSV files so I can check (send to bugs@bigomics.ch)?

Cheers. Ivo.

**Comment by c2b2pss** [comment]
> Hi c2b2pss. I tried the latest docker but cannot replicate your error using the example data. It may be some error in your data files. Can you please do the following?
> 
> 1. What version are you using?
> 2. Can you try the example data? Does that work?
> 3. If you try your own data, try selecting only limma.trend and fisher, and deselect all 'extra analysis'. Does that work?
> 4. Otherwise please can you send us your CSV files so I can check (send to [bugs@bigomics.ch](mailto:bugs@bigomics.ch))?
> 
> Cheers. Ivo.

Ignore my comment, please! Is the first error quoted by "Premsubr" fixed?

Thanks!

**Comment by ivokwee** [comment]
Hi c2b2pss. I have updated the git to v2.7.19 and the corresponding docker is bigomics/omicsplayground:testing. Can you see if you still have the same problem and test the steps above?

**Comment by c2b2pss** [comment]
Thanks, ivokwee!

Is the source version also fixed?

**Comment by c2b2pss** [comment]
Oops! Sorry, I misread the message.......git is updated!!

**Comment by c2b2pss** [comment]
What is the easiest way to update my source version from git? I am not very savvy with _updating_ packages from git.

**Comment by ivokwee** [comment]
To update your code just enter 'git pull' in the omicsplayground folder.

Again. I don't think it is fixed. But to have more information I need you to check the points I mentioned above.

**Comment by c2b2pss** [comment]
OK. Will do. Thanks!

**Comment by c2b2pss** [comment]
On the source version in R, I pulled the updates and now I get a new error:

[MakeContrast::UI] reacted
[ComputePgxServer:@enable] enabling compute button
DBG [LoadingBoard::inputData] ---------- reacted ---------------
DBG [LoadingBoard::inputData] AUTHENTICATION= none 
DBG [LoadingBoard::inputData] auth$logged= FALSE 
Warning in mapply(children, flex, FUN = function(el, flexValue) { :
  longer argument not a multiple of length of shorter
Warning: The 'plotly_restyle' event tied a source ID of 'pcoords' is not registered. In order to obtain this event data, please add `event_register(p, 'plotly_restyle')` to the plot (`p`) that you wish to obtain event data from.
DBG [BiomarkerBoard:<input_pdx_select>]  reacted
Warning: Error in <observer>: object 'COLLECTIONS' not found
  44: <observer> [boards/ClusteringBoard.R#1405]
   1: shiny::runApp
Warning in mapply(children, flex, FUN = function(el, flexValue) { :
  longer argument not a multiple of length of shorter
