### ISSUE TITLE
[UI] Tooltips

### ISSUE THREAD

**Issue by JohnCoene** [bigomics/omicsplayground#110]
We must redo the tooltips.
There's no need for 1 or 2 packages, it comes with standard HTML and is improved by Bootstrap.
Moreover, it lights up the console like a Christmas tree, I would not be surprised this is partly the cause for the app hanging on some browers.

**Comment by ivokwee** [comment]
Yes. Also the bsTooltips (we use the tipify()) that we now use, often give "lingering" labels that do not go away even if you move to different boards. I have experienced this and some users also. Currently, most tooltips are added using the function tipify() around the element, so it might be easy to overload/overwrite that function.
