### ISSUE TITLE
BETA: Uniprot IDs not always converted into HGNC Ids for mouse

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#1110]
This is an issue that has been raised by Cristopher Gonzales on the current Beta version (Omics Playground v3.5.0-rc2+master240923).

It seems that the platform is not always converting UNIPROT Ids into their corresponding HGNC Ids, see attached image.

For example, Q61410 should be translated as Prkg2 (https://www.uniprot.org/uniprotkb/Q61410/entry), but the platform is not doing it. 

![image](https://github.com/user-attachments/assets/4de85003-dda6-45c5-a31d-fe6f7faafc35)

**Comment by ivokwee** [comment]
resolved in https://github.com/bigomics/playbase/pull/148 and https://github.com/bigomics/playbase/pull/150.
