### ISSUE TITLE
BETA: Uniprot Ids not being correctly translated into MGI Ids for mice

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#1125]
This is an extension of a previous report regarding incomplete conversion of UNIPROT Ids into HGNC Ids (https://github.com/bigomics/omicsplayground/issues/1110).

 The issues is still affecting conversion from Mouse UNIPROT Ids into MGI Ids, where MGI ids exist in the UNIPROT database but are not being converted into MGI Ids, as reported by Cristopher Gonzales:

![image](https://github.com/user-attachments/assets/c260937f-aae4-41f5-b860-7a0f17c9e1fa)

As an example from the dataset above, see the following link:

https://www.uniprot.org/uniprotkb/F6TQW2/entry

**Comment by ivokwee** [comment]
Solved here https://github.com/bigomics/playbase/pull/154
