### ISSUE TITLE
[UI] random busy loaders at startup screen

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#115]
The busy loaders appear kind of random at the startup screen and "light up like a christmast tree" (John's wording...). Probably from elements created behing the startup screen. Maybe we can suppress these using proper z-level HTML/CSS?
 
![image](https://user-images.githubusercontent.com/19613146/162710846-04e9dda0-7192-4172-b6db-dbe0575c9391.png)

**Comment by stefanreifenberg** [comment]
I used johns waiter package and put the autowaiter in there to have some sort of feedback if the app is crashed or not. using specific waiters for specific elements will fix this

**Comment by JohnCoene** [comment]
I think changing the z-index of the loading screen may be easier

**Comment by JohnCoene** [comment]
Whatever we do, we'll need the loading screen to have a greater z-index than the loaders.

Also resigning the UI with a different loading page: reactives should not trigger on load so it'll fix itself eventually
