### ISSUE TITLE
Data upload:: Can't assign to the same column twice in the same query (duplicates detected).

### ISSUE THREAD

**Issue by zitoa** [bigomics/omicsplayground#1175]
Hubspot ticket: 9841247224

80: h
   79: .handleSimpleError
   78: [.data.table
   77: [
   76: read.as_matrix
   75: playbase::read_annot
   74: observe
   73: <observer:observeEvent(input$counts_csv)>

**Comment by ESCRI11** [comment]
Important as this actually crashes app with blue screen; also found in 5 different tickets (from different users all)

![image](https://github.com/user-attachments/assets/9db63eb6-d5d3-4dd9-85cc-9c8adecaa74d)
