### ISSUE TITLE
Cluster > Sampes: undefined columns selected

### ISSUE THREAD

**Issue by ESCRI11** [bigomics/omicsplayground#1231]
Hubspot ticket 17288583385

![image](https://github.com/user-attachments/assets/9677ac20-a3cb-4495-8f0f-4af8e8666d2c)

Probably because we use `pgx$Y`, which is being substituted by the user of `pgx$samples`.

**Comment by zitoa** [comment]
@ESCRI11 I've just fixed this. See PR #1238 which fixes issue #1237 .

Issue was more convoluted. Also added shiny::validate. If you and @ivokwee approve. let's merge
