### ISSUE TITLE
platform issue?

### ISSUE THREAD

**Issue by Ax-h3ll** [bigomics/omicsplayground#1259]
Hi,

I am having several issues today on the bigomics platform. Maybe some of them are my lack of knowledge. So sorry if that is the case.

1- I can't access the editing window for any graph the message that I get is : pro.playground.bigomics.ch n'autorise pas la connexion (pro.playground.bigomics.ch does not allow connexion) 
<img width="1492" alt="Capture d’écran 2024-11-07 à 11 47 25" src="https://github.com/user-attachments/assets/fef635ba-b3de-41fe-b5d9-27a7fac27155">

2- whenever I try to change the scale in a graph (using my trackpad since the editing window does not work), it does not appear when I download it. I have to take screenshots to be able to use them with the changes. Also, I do not have the small camera to download graphs directly from the enlarged version (but I think this is linked to the editor so I supposed it was because I couldn't access it).

3- some graph do not have anything on them when I download them as png. PDF work though. I don't know if it is normal?
![clustersamples-parcoord-pltmod (1)](https://github.com/user-attachments/assets/4d783d19-ec54-4da6-baeb-0d501cbd2050)
[clustersamples-parcoord-pltmod (1).pdf](https://github.com/user-attachments/files/17668635/clustersamples-parcoord-pltmod.1.pdf)

4- in the parallel section of the cluster sample it says that : you can manally (I think the correct word is manUally but not the real issue here) order the time point, but whenever I try to do something, it just says 0 entry, (by the way how do I go back? because usually I have to quit and log back on again to cancel a selection. Or change it to select the full data, isn't there a way to just click back to reset?).
<img width="1131" alt="Capture d’écran 2024-11-07 à 11 45 23" src="https://github.com/user-attachments/assets/1ff9190d-5dd5-4a2d-a5d5-41053f690990">

5- is it normal that when I changed the plot version, I had more than half of my data that just disapeared?
<img width="1082" alt="Capture d’écran 2024-11-07 à 10 00 40" src="https://github.com/user-attachments/assets/20bb72a5-c051-4bfa-8a69-f7f774fc097d">
<img width="1082" alt="Capture d’écran 2024-11-07 à 10 00 54" src="https://github.com/user-attachments/assets/1ea770f5-9bbe-4ebc-aba6-185c16688e9b">
![dataview-expressionplot-pltmod](https://github.com/user-attachments/assets/f79b269c-ef2d-4262-a72e-e46b1d8585e5)

6- I had one more issue today when downloading the clustering feature geneset table, I get weird names for the genesets (adding text, and I have tried to download it as csv and excel sheets, it does not change anything). Furthermore, the data I got before and what I get today are not even the same with the same dataset... (this is an issue I am having quite frequently datatreatment changing the outcome each time I log back on...)
<img width="1168" alt="Capture d’écran 2024-11-07 à 15 54 52" src="https://github.com/user-attachments/assets/9877421a-147d-4d74-a29e-9e4ff2b181cc">
![Capture d’écran 2024-11-07 à 15 57 33](https://github.com/user-attachments/assets/1685338a-193d-4127-a69b-f96566b78067)

Ok that pretty much covers it for today.
Thanks for your help.
Best.

**Comment by ESCRI11** [comment]
Hello @Ax-h3ll we are looking into your inputs. We will get back to you as soon as possible

**Comment by ESCRI11** [comment]
Also, please @Ax-h3ll could you send us the name of the dataset that you are visualizing, that way it will be easier for the dev team to double check the issues

**Comment by Ax-h3ll** [comment]
I use 2 separate datasets called:

Mice_lung | + mitocarta 19 celltypes | Mouse | scRNA-seq | 1234 | 14372 | state celltype celltype_state | 2024-10-31 | 
 
  | CIH_Lung_Male_mice_Prelim | CIH Lung Male mice Prelim | Mouse | scRNA-seq | 1234 | 14372 | state celltype celltype_state 2024-08-12

**Comment by Ax-h3ll** [comment]
Also, just to add some clarity, for the point 6, in the printscreen of the presented table, the one below was downloaded 2 weeks ago from the  | CIH_Lung_Male_mice_Prelim | CIH Lung Male mice Prelim | Mouse | scRNA-seq | 1234 | 14372 | state celltype celltype_state 2024-08-12
But I am not sure if I used the exact same parameters for the second one, so here is an excel file containing the exact table I get today versus october 15 for the same datasets using the exact same parameters. 
Data are the same (so that part was on me), but presentation presents a problem. :) 
[clusterfeatures-gsetUMAP-gset_table-table trouble.xlsx](https://github.com/user-attachments/files/17682030/clusterfeatures-gsetUMAP-gset_table-table.trouble.xlsx)

**Comment by ESCRI11** [comment]
Hello @Ax-h3ll , quick update.

Point 1: The plot editor should be accessible now, tank you for the heads up.

Point 2: It is a known issue, we hope that with point 1 solved, you can get around it.

Point 3: Work in progress, again, I think point 1 solves the problem for you, nevertheless it is something we are looking into.

Point 4: If you click on the selection it gets removed, here a small video: 

[Screencast from 2024-11-11 10-09-39.webm](https://github.com/user-attachments/assets/fe73d72f-f5c1-4789-95a0-1119ff47ad92)

Point 5: Fixed here (https://github.com/bigomics/omicsplayground/pull/1260)

Point 6: Fixed here (https://github.com/bigomics/omicsplayground/pull/1260)

Thank you for your input. The code changes are now under review by the dev team and will probably be live on the platform in 1 to 2 days. If you want, I can ping you when that happens, let me know.

**Comment by ESCRI11** [comment]
@Ax-h3ll You should be able to see the changes on the platform.
