### ISSUE TITLE
Error in if: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by sooheon** [bigomics/omicsplayground#126]
I am seeing the following error on import. 

```
>>> Testing differential expressed genes (DEG) with methods: trend.limma deseq2.wald edger.qlf
[compute.testGenesSingleOmics] 12 : start fitting...
[ngs.fitContrastsWithAllMethods] calculating methods : trend.limmadeseq2.waldedger.qlf
[ngs.fitContrastsWithAllMethods] prune.samples = FALSE
[ngs.fitContrastsWithAllMethods] 2 :
[ngs.fitContrastsWithAllMethods] using input log-expression matrix X...
[ngs.fitContrastsWithAllMethods] [ngs.fitContrastsWithAllMethods] 3 :
[ngs.fitContrastsWithAllMethods] fitting using LIMMA trend
[ngs.fitContrastsWithLIMMA] fitting LIMMA contrasts using design matrix
[ngs.fitContrastsWithAllMethods] fitting edgeR using QL F-test
Warning in edgeR::DGEList(round(counts), group = NULL) :
  library size of zero detected
Timing stopped at: 0.077 0 0.077
Warning: Error in if: missing value where TRUE/FALSE needed
  1: shiny::runApp
```

Appears to be something about the data edgeR.qlf does not expect, so I tried running without any missing values in counts or samples, but the error continues. What could be causing this issue?

**Comment by sooheon** [comment]
Unchecking edger.qlf in the advanced compute options avoids the error, but I'm still curious how to fix this.

**Comment by ivokwee** [comment]
`library size of zero detected`

Perhaps one of your columns is zero. If you have relative values, you need to add constant and exponentiate. You see that we use `round(counts)`. Yes, please infer missing values yourself. The platform regards missing values as zero otherwise.

**Comment by sooheon** [comment]
To be clear, the files are zero mean, but I made sure to upload as expressions.csv

**Comment by ivokwee** [comment]
Hi Sooheon. Please add (about) 5-6 to the zero-mean values for now, otherwise your "pseudo-counts" will be too low for edgeR or DEseq2.

**Comment by sooheon** [comment]
Thanks, yeah this works.
