### ISSUE TITLE
Start Button overlaps with text on certain loading screens

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#129]
<img width="613" alt="Screenshot 2022-04-22 at 13 51 40" src="https://user-images.githubusercontent.com/15939539/164720081-81088f58-f71b-4839-995a-6fa3cf96e7e1.png">

**Comment by ivokwee** [comment]
The modal is now bigger. Resolved. However would be nice to recode the modal with more responsive (adaptable) elements.
