### ISSUE TITLE
Downward arrow with no function above heatmap plot

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#134]
<img width="279" alt="Screenshot 2022-04-22 at 15 31 52" src="https://user-images.githubusercontent.com/15939539/164724502-81e116f5-d4a4-405b-9c10-b8a79fe15849.png">

**Comment by ivokwee** [comment]
Notice also the small dot left of the hamburger icon. Thi is also a chevron. The problem is in the CSS `html .dropdown-toggle::after` which creates a chevron after every dropdown. We need to restrict it only to the menu items in the UI menus, top bar.
