### ISSUE TITLE
Sidebar overlapping on small screens

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#137]
<img width="375" alt="Screenshot 2022-04-22 at 15 58 52" src="https://user-images.githubusercontent.com/15939539/164729444-2a79b7ca-1dd9-4dda-8eb6-9e34db2bc007.png">

**Comment by ivokwee** [comment]
I already changed the line spacing. Should be less probable now. To avoid we could put the menu in an overflow container.

**Comment by ivokwee** [comment]
like this, the mascotte remaining. And even disappear all together (i.e. the help-info) if more space is needed.

![image](https://user-images.githubusercontent.com/19613146/165488254-eb3a17fb-7e23-4e13-b9ff-233a38876337.png)
![image](https://user-images.githubusercontent.com/19613146/165488702-4feed387-cb67-404a-a28b-cf721182894b.png)
