### ISSUE TITLE
DataView, CellProfiling, Sidebar Arrows greyed out on startup

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#142]
<img width="244" alt="Screenshot 2022-04-25 at 19 14 34" src="https://user-images.githubusercontent.com/15939539/165140087-03e628ef-8b54-42da-8b59-5c104dd76e68.png">

**Comment by ivokwee** [comment]
Looks like they are the one without submenu?

**Comment by ivokwee** [comment]
seems solved
