### ISSUE TITLE
After logout/login menu is not reset to welcome state

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#152]
After logout/login (change of user), the full menu is expanded. Menu items, except for 'Load', should be hidden and page should go back to welcome screen (as in first login). Menu (except 'Load') should be hidden if no data is loaded or active.

![image](https://user-images.githubusercontent.com/19613146/167437247-3859343f-95d9-4afe-bd7a-e6457a3b7a11.png)

**Comment by JohnCoene** [comment]
Fixed in `develop`

**Comment by ivokwee** [comment]
Not really. Should be set to NULL for security
