### ISSUE TITLE
MV Imputation strategies

### ISSUE THREAD

**Issue by L4ft2di3** [bigomics/omicsplayground#16]
I would love to see the implementation of MV imputation strategies into the platform.

Kind regards
Thorben

**Comment by bigomics** [comment]
OK Noted. 

Can you tell us which methods you use and which are the most widely used (assuming in proteomics)? Can you give us some references for these missing values strategies? Perhaps a example file with missing values that you often use and perhaps know with strategy works best? This would help.

Ivo

**Comment by L4ft2di3** [comment]
Hey Ivo,

well I dont have much experience in MV handling and am tinkering around with it at the moment, which is why I opened this request. However, there are some interesting approaches in the literature:

Välikangas et al. found the local least square regression imputation as consistently improving the differential expression analysis.
https://pubmed.ncbi.nlm.nih.gov/28575146/

Lazar et al. compared different imputation strategies in regard to their nature and came to the conclusion that MAR and MNAR should be handled differently. The bioconductor package "DEP" from Arne Smits utilizes this mixed imputation strategy.
https://pubs.acs.org/doi/10.1021/acs.jproteome.5b00981
https://bioconductor.org/packages/release/bioc/html/DEP.html

Unfortunately, I can not provide an example file with missing values where I know that a certain strategy works good, since as I said above, I don't really have experience with this kind of data. So far, we typically filtered the data for complete proteins or used imputation strategies based on normalized distributions.

I hope this helps.

All the best,
Thorben
