### ISSUE TITLE
Omicsplayground not running anymore

### ISSUE THREAD

**Issue by DaliJarboui** [bigomics/omicsplayground#161]
Following the last updates the app is not running anymore, doesn't load data (that used to work with older versions), not even the example data already exciting????
I'm using the app using the docker file (1st installation method).
appreciate if there is any help or advice to make it run again.
Regards

**Comment by ivokwee** [comment]
Hi Dali. Can you pull the latest docker please? It should be v2..8.10  For me this version should work. Otherwise, please use the online version  playground.bigomics.ch
