### ISSUE TITLE
wordcloud error

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#165]
For a small dataset, perhaps when no genesets are significant, the wordcloud module gives an error during pre-computation.

[Axel 16.08.2022]

------------------------------
>>> computing WordCloud statistics...
Timing stopped at: 0.575 0 0.575
Warning: Error in if: missing value where TRUE/FALSE needed
  1: shiny::runApp
******** doing session cleanup ********
DBG [MAIN.logHandler] >>>>> called! <<<<<

**Comment by ivokwee** [comment]
need to be checked again

**Comment by mauromiguelm** [comment]
no new report, axel should reopen if we find the problem again
