### ISSUE TITLE
Orca-server not starting - Shiny-Server Install

### ISSUE THREAD

**Issue by bluedominion** [bigomics/omicsplayground#2]
I've been working on setting up a stand-alone instance on shiny-server, and kept getting a "something went wrong" error where the shiny app wouldn't load.  Looking at the logs (attached), it boils down to the orca server not starting under shiny.  I made sure it was in my path, I made sure it wasn't an issue with X11 forwarding, pretty much everything I could find.  Eventually, I got it to work by running orca server in a docker container ("docker pull quay.io/plotly/orca") , and commenting out the lines that create the orca server and specifically check the local instance in shiny/global.R as below:

1) docker run --name orca_server -p 5151:9091 quay.io/plotly/orca (next time I'll run with the -d flag)
2) comment out "ORCA <- plotly::orca_serve(port=5151, keep_alive=TRUE, more_args="--enable-webgl")" and "message("local ORCA is alive = ",ORCA$process$is_alive())" lines in shiny/global.R

[omicsplayground-kraig-20200812-154813-46793.log](https://github.com/bigomics/omicsplayground/files/5066312/omicsplayground-kraig-20200812-154813-46793.log)

Relevant log section below:

`*****************************************
***** starting local ORCA server ********
'*****************************************
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(orca:6886): dbind-ERROR **: 15:48:20.326: AT-SPI: Couldn't connect to accessibility bus. Is at-spi-bus-launcher running?
Trace/breakpoint trap (core dumped)
Warning in system("orca --version", intern = TRUE) :
  running command 'orca --version' had status 133
Error in if (orca_version() >= "1.1.1") "--graph-only" : 
  argument is of length zero
Calls: runApp ... source -> withVisible -> eval -> eval -> <Anonymous>
Execution halted`'

System Info:
Ubuntu 18.04 LTS
Shiny Server v1.5.12.933 (Node.js v10.15.3)
Docker v19.03.12
(Let me know what other info is relevant and I will add it)

**Comment by bigomics** [comment]
Hi. 

Thanks for reporting. Sorry about the orca problem, recently the old Plotly export didn't work anymore and we needed to switch to orca. Good you found a solultion. 

Can you show your orca path using 'which orca'? One problem is that at least in Ubuntu can be a different program. In Ubuntu /usr/bin/orca is a screen reader program so you would need to remove the orca Ubuntu package, or rename the /usr/bin/orca binary.

In the Docker image we installed the orca AppImage from GitHub (https://github.com/plotly/orca) and put it in /usr/local/bin/orca-1.3.1.AppImage (then linking to /usr/local/bin/orca). The Playground tries to launch a local orca-server and connect to it, if not it actually looks for a docker running but it seems it even didn't try that in your case (so the orca screen read may be the culprit...). This should actually also work when launching the Playground through a local shiny-server. We will try to make this robust in next versions. 

Thanks!

Ivo

**Comment by bluedominion** [comment]
When I run 'which orca' I get: /<home directory>/anaconda3/bin/orca  (which I do have added to my $PATH, but likely isn't part of shiny's $PATH), and you're right, there is a /usr/bin/orca, and that could definitely cause problems.  I thought about going the appimage route, but wasn't sure how to change the global.R script to call that instead of the plotly version.  I suspect you're right that the local orca in Ubuntu is probably breaking things.

**Comment by bigomics** [comment]
The orca_serve() function in the plotly package looks for the first 'orca' executable it can find. I don't known if I can specify the path there. But I had the same error and took me also a while to understand what was happening...  

I now modified the Orca initialization a bit. The code is moved from global.R to pgx-modules.R. It now first tries to find the Orca server on dockers ( on http://orca-server:9091 or http://localhost:9091), then if those are not available, any already running local Orca server (at http://localhost:5151), and finally tries to launch a new server with orca_serve()  (which still has the problem of /usr/bin/orca as screen reader). If you launch a dockerized orca server (like you did), it should now work without hacking the code.  In future, we will probably use the orca docker solution using docker-compose.

Thanks. Ivo.
