### ISSUE TITLE
Omicsplygrd not starting: connect to fonts.googleapis.com  timed out

### ISSUE THREAD

**Issue by DaliJarboui** [bigomics/omicsplayground#207]
Trying to use the new version (Docker), everything seems to be fine with no issues, however when I try to open http://localhost:4000/, I have the error : 
An error has occurred!
Timeout was reached: [] Failed to connect to fonts.googleapis.com port 443 after 5218 ms: Connection timed out

I used omicsplayground before and was not such an error. (older versions).

Thanks for your help.

**Comment by ivokwee** [comment]
Thanks for the bug report. We will look into that. We are currently testing a new version so the latest docker is pretty unstable. For a stable version please use the docker bigomics/omicsplayground:latest-v2 or bigomics/omicsplayground:stable
