### ISSUE TITLE
Unlocking package internals

### ISSUE THREAD

**Issue by JohnCoene** [bigomics/omicsplayground#21]
Why do we unlock package internals?

https://github.com/bigomics/omicsplayground/blob/6b63672ab5eddd28f8818242d540ca695ab9cf5e/shiny/boards/FunctionalBoard.R#L280

I'm asking because this requires the package to be loaded in the global environment; we can't use the namespace for `pathview`

**Comment by ivokwee** [comment]
There was/is a bug in pathview::geneannot.map() so we had to override that function with our own function my.geneannot.map()  We should actually report the but and see if it is corrected in the latest pathview package.

**Comment by JohnCoene** [comment]
Shouldn't be using pathview, license does not permit it. Can we remove that dependency?
