### ISSUE TITLE
top genes plot too wide in zoomed plot

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#210]
The top genes plot in diff expr is too wide and needs to scroll in the modal windows. Need to adjust width to screen. 

![image](https://user-images.githubusercontent.com/19613146/224520855-ef75d30f-7711-4c43-9af4-c770e3874dfb.png)

**Comment by ivokwee** [comment]
same for volcanos (all)

![image](https://user-images.githubusercontent.com/19613146/224520957-fbf2e359-b520-43e2-b197-1960932e8b29.png)

**Comment by mauromiguelm** [comment]
this will be done with layout_column wrap implementation of cards

**Comment by ivokwee** [comment]
done. now modal width is forced to 100% in PlotModule.
