### ISSUE TITLE
volcano plots should be done in plotly

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#212]
Volcano plots (all and methods) should be done in plotly. We need to see if it becomes too heavy for the client browser or try subsampling. Also see if we should put all plots in a panel or separate too improve responsiveness in mobile layout.

![image](https://user-images.githubusercontent.com/19613146/224521316-54c6ee05-49bb-48f8-8246-ddbc6a97e668.png)
![image](https://user-images.githubusercontent.com/19613146/224521328-2ccd87fc-9eb4-44e7-a2ef-39f64b6269d1.png)

**Comment by mauromiguelm** [comment]
this will be done with layout_column wrap implementation of cards

**Comment by ivokwee** [comment]
Closing this. Currently redone in ggplot. Plotly is heavy (and not needed) if many scatter or volcanos need to be shown. Need to rethink.
