### ISSUE TITLE
ModuleNotFoundError: No module name 'plotly'

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#213]
download of PNG and PDF do not work. I get an empty plot, blank page. image is 0bytes.

**Comment by ivokwee** [comment]
I got this error. Maybe it's my installation,

![image](https://user-images.githubusercontent.com/19613146/224521732-d88eb168-9ae8-4050-80fa-f1296aa9277e.png)

**Comment by ivokwee** [comment]
Solved. My Kaleido mini-conda installation was corrupted. Had to reinstall using according to https://search.r-project.org/CRAN/refmans/plotly/html/save_image.html .  Works again.

```
install.packages('reticulate')
reticulate::install_miniconda()
reticulate::conda_install('r-reticulate', 'python-kaleido')
reticulate::conda_install('r-reticulate', 'plotly', channel = 'plotly')
reticulate::use_miniconda('r-reticulate')
```

**Comment by ESCRI11** [comment]
@ivokwee For future reference, I added some days ago a Wiki article to setup the `reticulate` environment for omicsplayground

https://github.com/bigomics/omicsplayground/wiki/%60recticulate%60-setup
