### ISSUE TITLE
Warning - gx-heatmap

### ISSUE THREAD

**Issue by JohnCoene** [bigomics/omicsplayground#22]
https://github.com/bigomics/omicsplayground/blob/c129c58008bced30d699661868f7d16cc50a0725/R/gx-heatmap.r#L1226

Is this warnin supposed to fire when `dendrogram <- "none"` or all the time?

**Comment by ivokwee** [comment]
seems ok. see also line 1236 repeated like that. not our code originally. but in 1225 it had a spelling error.
