### ISSUE TITLE
Volcano (methods) at Differential Expression should be ggplot or better plotly

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#236]
Volcano (methods) at Differential Expression should at least be ggplot like volcano (all) .. (or better entirely in plotly).

**Comment by ivokwee** [comment]
Same for volcano (all) and volcano (methods) in geneset enrichment.

**Comment by mauromiguelm** [comment]
this will be done with layout_column wrap implementation of cards

**Comment by ivokwee** [comment]
done. ggplot for now.
