### ISSUE TITLE
Refactor PlotModule with Bootstrap 5 components/cards

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#245]
Would be good to refactor the PlotModule, or starting part of it, to refactor with BS5 or BS5 cards. We have problems with height and positioning captions in the PlotModule. Hopefully using standard BS5 elements this would improve responsiveness and layout consistency. For example now with the PlotModule, the height needs to be often given to both container and again for plot/tables within. The caption on the bottom of the PlotModule is not at all aligned at the bottom of the container. Perhaps going to BS5 cards, this would be automatically aligned.

**Comment by mauromiguelm** [comment]
done on #250
