### ISSUE TITLE
Heatmap splitting on genes gives sometimes wrong high/low label

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#248]
Splitting the heatmap on gene status under the options, gives sometimes a incorrect wrong label of high/low in the resulting heatmap. To replicate:

1. Use example-data.pgx
2. Split heatmap on gene MKI67
3. Heatmap is correctly split as below but MKI67 high/low labels are wrongly reversed

![image](https://user-images.githubusercontent.com/19613146/226200952-334211ad-1c3c-4e07-9d4f-615d627e6739.png)

**Comment by ivokwee** [comment]
can someone check and close?

**Comment by ESCRI11** [comment]
Double checked. Looks good
