### ISSUE TITLE
Delete button from loading board sometimes does not work

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#275]
- sometimes the delete option on the sweet alert does not work
- it would be nice to have the old basic buttons in addition to the table options, that would speed up deleting datasets

**Comment by ivokwee** [comment]
bug confirmed. the sweetalert is not coming up consistently. something with the reactivity.

**Comment by ivokwee** [comment]
I think it happens when you want to delete a dataset, cancels, and try to delete again.
