### ISSUE TITLE
Arrange JavaScript

### ISSUE THREAD

**Issue by ESCRI11** [bigomics/omicsplayground#284]
The JavaScript `temp.js` file needs housekeeping, either move to `bigdash` or create different `.js` files with correct naming.

**Comment by ivokwee** [comment]
Same for CSS. Maybe @mauromiguelm can do that?

**Comment by mauromiguelm** [comment]
yes, we should move most if not all js and scss code to bigdash, so its reusable in the future. I will start doing that this and next week. I will discuss details on Slack

**Comment by ivokwee** [comment]
Not sure if these artifical JS clicks are the way to do things, rather than directly editing the elements/class. Looks more like a hack... but hey it works....

**Comment by ivokwee** [comment]
Is this done? @ESCRI11  If most of it is mostly done, we can close this issue and still work on it gradually.

**Comment by ivokwee** [comment]
closing stale issue. perhaps in mean time already done by xavier.
