### ISSUE TITLE
Some plots cannot be downloaded PNG/PDF

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#289]
These plots cannot be downloaded as PNG/PDF:

Cluster features > Gene > Gene Signatures  (base plot)
Cluster features > Geneset > Geneset Signatures  (base plot)
Correlation analyis > Graph > Partial correlation network (visnetwork)
Correlation analyis > Graph > Partial correlation network (visnetwork)
Geneset enrichment > Top enriched > Top enriched gene sets (base)
Geneset enrichment > Plots > Volcano plot (base)
Geneset enrichment > Plots > Enrichment vs. expression (base)
Pathway analysis > Pathway Analysis > GO graph
Word cloud > Word cloud > Enrichment plots (base)
Word cloud > Word cloud > Word Cloud (base)
Drug Connectivity   > Drug enrichment > Activation matrix (base)
Compare signatures   > Pairwise scatter > Venn diagram
Similar experiments   > FC Heatmap > Connectivity heatmap (base?)
Similar experiments   > Meta-graph > Leading-edge graph (visnetwork)
Similar experiments   > Meta-graph > Enrichment graph (visnetwork)
Single Cell Board > Cell type > Cell type profiling (ggplot/grid)
Single Cell Board > Markers > Expression of marker genes (ggplot/grid)
Single Cell Board > Markers > Cytometry  plot (ggplot/grid)
Compare datasets (beta) > Compare expression > Dataset1 (base)
Compare datasets (beta) > Compare expression > Dataset2 (base)
Compare datasets (beta) > Gene Correlation > Expression (base)
Compare datasets (beta) > Gene Correlation > Gene correlation (base)
TCGA (beta) > TCGA survival > TCGA survival analysis (base)
Clustering > WGCNA (beta) > WGCNA > Gene dendrogram and gene modules (base)
Clustering > WGCNA (beta) > WGCNA > Scale independence and mean connectivity (base)
Clustering > WGCNA (beta) > WGCNA > TOM heatmap (base)
Clustering > WGCNA (beta) > WGCNA > Gene clustering (base)
Clustering > WGCNA (beta) > WGCNA > Module graph (base)
Clustering > WGCNA (beta) > Modules > Module-Trait relationships (base)
Clustering > WGCNA (beta) > Modules > Correlation network (base)
Clustering > WGCNA (beta) > Modules > Correlation network2 (base)
Clustering > WGCNA (beta) > Eigengenes > Eigengene clustering (base)
Clustering > WGCNA (beta) > Eigengenes > Module membership (eigengene correlation)
Clustering > WGCNA (beta) > Intramodular > Membership-trait heatmap
Clustering > WGCNA (beta) > Intramodular > Membership vs. trait correlation

**Comment by ivokwee** [comment]
Not solved. For the first 5-6 plots I still get a download error. Base plot render function need to be pure functions, not reactives. The solution for now is to take out   `grDevices::recordPlot()`  and making the RENDER a pure function (instead of reactive). This seems to work. 

![image](https://user-images.githubusercontent.com/19613146/232739252-bb783fbb-b085-459f-8f16-4c55f839be09.png)

**Comment by mauromiguelm** [comment]
Hi Ivo,

I fixed on Cluster features > Gene > Gene Signatures (base plot), could you check if its working for you? I will then go plot by plot if there's no other solution

https://github.com/bigomics/omicsplayground/tree/fix-plot-download

**Comment by ivokwee** [comment]
works. please do the rest. Not sure if the visnetworks have similar problem.
![plot (27)](https://user-images.githubusercontent.com/19613146/232930623-2ea9012d-f61c-4abf-9cf1-47093061dfcd.png)

**Comment by ivokwee** [comment]
[OK] Cluster features > Gene > Gene Signatures (base plot)
[OK] Cluster features > Geneset > Geneset Signatures (base plot)
[failed] Correlation analyis > Graph > Partial correlation network (visnetwork)
[failed] Correlation analyis > Graph > Partial correlation network (visnetwork)
[OK] Geneset enrichment > Top enriched > Top enriched gene sets (base)
[OK] Geneset enrichment > Plots > Volcano plot (base)
[OK] Geneset enrichment > Plots > Enrichment vs. expression (base)
[failed] Pathway analysis > Pathway Analysis > GO graph
[failed] Word cloud > Word cloud > Enrichment plots (base)
[failed] Drug Connectivity > Drug enrichment > Activation matrix (base)
[OK] Compare signatures > Pairwise scatter > Venn diagram
[OK] Similar experiments > FC Heatmap > Connectivity heatmap (base?)
[failed] Similar experiments > Meta-graph > Leading-edge graph (visnetwork)
[failed] Similar experiments > Meta-graph > Enrichment graph (visnetwork)
[OK] Single Cell Board > Cell type > Cell type profiling (ggplot/grid)
[png=OK,pdf=failed] Single Cell Board > Markers > Expression of marker genes (ggplot/grid)
[failed] Single Cell Board > Markers > Cytometry plot (ggplot/grid)
[OK] Compare datasets (beta) > Compare expression > Dataset1 (base)
[OK] Compare datasets (beta) > Compare expression > Dataset2 (base)
[OK] Compare datasets (beta) > Gene Correlation > Expression (base)
[OK] Compare datasets (beta) > Gene Correlation > Gene correlation (base)
[OK] TCGA (beta) > TCGA survival > TCGA survival analysis (base)
[OK] Clustering > WGCNA (beta) > WGCNA > Gene dendrogram and gene modules (base)
[OK] Clustering > WGCNA (beta) > WGCNA > Scale independence and mean connectivity (base)
[OK] Clustering > WGCNA (beta) > WGCNA > TOM heatmap (base)
[OK] Clustering > WGCNA (beta) > WGCNA > Gene clustering (base)
[OK] Clustering > WGCNA (beta) > WGCNA > Module graph (base)
[failed] Clustering > WGCNA (beta) > Modules > Module-Trait relationships (base)
[OK] Clustering > WGCNA (beta) > Modules > Correlation network (base)
[failed] Clustering > WGCNA (beta) > Modules > Correlation network2 (base)
[OK] Clustering > WGCNA (beta) > Eigengenes > Eigengene clustering (base)
[OK] Clustering > WGCNA (beta) > Eigengenes > Module membership (eigengene correlation)
[OK] Clustering > WGCNA (beta) > Intramodular > Membership-trait heatmap
[OK] Clustering > WGCNA (beta) > Intramodular > Membership vs. trait correlation

**Comment by mauromiguelm** [comment]
**My comments in bold for the ones not working:**

**Visnetwork:**
[failed] Correlation analyis > Graph > Partial correlation network (visnetwork)
[failed] Correlation analyis > Graph > Partial correlation network (visnetwork)
[failed] Pathway analysis > Pathway Analysis > GO graph **(also visnetwork)**
[failed] Similar experiments > Meta-graph > Leading-edge graph (visnetwork)
[failed] Similar experiments > Meta-graph > Enrichment graph (visnetwork)

For visnetwork, run webshot::install_phantomjs() and install dependencies, it should work after that. 

**Not visnetwork:**
[failed] Word cloud > Word cloud > Enrichment plots (base) **working for me**
[plot (6).pdf](https://github.com/bigomics/omicsplayground/files/11295567/plot.6.pdf)
[failed] Drug Connectivity > Drug enrichment > Activation matrix (base) **not working, check.. its corrplot assigned as base**
[png=OK,pdf=failed] Single Cell Board > Markers > Expression of marker genes (ggplot/grid) **investigate**
[failed] Single Cell Board > Markers > Cytometry plot (ggplot/grid) **investigate**
[failed] Clustering > WGCNA (beta) > Modules > Module-Trait relationships (base) **investigate**
[failed] Clustering > WGCNA (beta) > Modules > Correlation network2 (base) **investigate**

I am going through the plots that are not related to visnetwork.
