### ISSUE TITLE
comeback of static heatmap?

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#296]
I know that some othre users also mentioned the static heatmap, maybe we can bring it back in the near future

**Axel:**

I see you went for the interactive heatmap by default. Personally I miss the non-interactive form, as I liked the color scheme and sharpness better

**Comment by ESCRI11** [comment]
Yes, sorry for the delay I will work ASAP on making #253 PR available on master and place both heatmaps

**Comment by ivokwee** [comment]
this is not too urgent...

**Comment by ESCRI11** [comment]
Solved on #253
