### ISSUE TITLE
Data files processed with older scripts break startup

### ISSUE THREAD

**Issue by bluedominion** [bigomics/omicsplayground#3]
I recently started using omicsplayground, and started with the docker version.  It seemed to work, then seemed to randomly break.  Upon further investigation (and checking with the other install I have set up), it seems that some of the older data scripts keep the whole thing from starting.  The main culprit I've seen is GSE98638-scliver.pgx (script to create it is scripts/pgx-GSE98638-scliver.)  Removing that file from the data folder allows the entire software to function again.  

The log file section when this happens is:
`
'*****************************************
******** parsing OPTIONS file ***********
*****************************************'

TITLE   =  Omics Playground
USER_MODE       =  PRO
AUTHENTICATION  =  none
ENABLE_UPLOAD   =  TRUE
MAX_SAMPLES     =  20
MAX_COMPARISONS         =  5
MAX_GENES       =  19999
WATERMARK       =  TRUE
DEV_VERSION     =  FALSE
MODULES_DISABLED        =  tcga multi

Error in `rownames<-`(`*tmp*`, value = character(0)) :
  attempt to set 'rownames' on an object with no dimensions
Calls: runApp ... pgx.initDatasetFolder -> pgx.initDatasetFolder1 -> rownames<- -> rownames<-
Execution halted
`

Is there any way to rework things such that the app throws a more visible error for bad files?

**Comment by ivokwee** [comment]
True. Some scripts were still using some old style code (those sourcing the compute scripts) and their PGX files would have been broken/incomplete. I have updated all scripts, but I am still rebuilding the pgx files.   The problem should not exist anymore. Thanks for reporting.

**Comment by ivokwee** [comment]
True. Some pgx scripts were still using some old style code (those sourcing the compute scripts) and their PGX files would have been broken/incomplete. I have updated all scripts now, but I am still rebuilding the pgx files. The problem should not exist anymore. Thanks for reporting.

**Comment by ivokwee** [comment]
True. Some pgx scripts were still using some old style code (those sourcing the compute scripts) and their PGX files would have been broken/incomplete. I have updated all scripts now, but I am still rebuilding the pgx files. The problem should not exist anymore (Git version). Thanks for reporting.
