### ISSUE TITLE
Problem in biomarker discovery heatmap

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#300]
Axel, across many datasets:

![image](https://user-images.githubusercontent.com/28757711/231739490-980ebaa7-391f-4ab2-8052-54abe0a37f59.png)

**Comment by ESCRI11** [comment]
This is happening because the playbase/omicsplayground separation. The function `is.categorical` is defined here https://github.com/bigomics/playbase/blob/main/R/pgx-functions.R#L751

**Comment by ESCRI11** [comment]
I can reproduce the error on the beta deployment. However, when I run locally the latest OPG with the latest `playbase` installed it works OK (in both cases using test dataset)

@ivokwee Could it be that the deployment server does not automatically get the latest `playbase` release?

**Comment by ivokwee** [comment]
already solved. function is in playbase.
