### ISSUE TITLE
improve color of `Cell type profiling`

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#301]
Axel:

![image](https://user-images.githubusercontent.com/28757711/231739654-19a78ebd-7761-4185-9e06-66697c88081c.png)

**Comment by ivokwee** [comment]
not sure what is the problem. please describe more details.

**Comment by mauromiguelm** [comment]
Axel:

 I’m confused by the new colour scheme. For example, I have an experiment consisting of fibroblasts and I get the following results:



Now, the first plot is, as expected, indicating that the closest match are indeed fibroblasts. However, the dark grey colour to me indicates a poor match. Instead the red coloured samples In the Uterus, Artery and Ovary plot draw my attention as potential matches, although they are completely wrong. I find this very confusing. I preferred the system implemented in V2, where good matches were highlighted in various shades between dark red and grey,

Also, I’m getting an error message when trying to display the “proportions” plot when using the tissue (GTEX), Cell Line (HPA) and the Immuncell (DICE) databases. The error is repeated across multiple tested datasets:

**Comment by ivokwee** [comment]
I guess the scale needs to be fixed for all plots simultaneously. Probably the colorscale is now normalized for each plot.
