### ISSUE TITLE
error in `compare datasets` tab

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#302]
Axel:
I’m getting an error in the `compare datasets` tab:
![image](https://user-images.githubusercontent.com/28757711/231740032-b0161d98-3256-4e01-90d9-749c0fe82017.png)

**Comment by ivokwee** [comment]
The SPOM should have been solved. It's in playbase. Note it is called now playbase::plot_SPLOM()

**Comment by ivokwee** [comment]
bar is also recently solved. closing.
