### ISSUE TITLE
Background computation is broken ***urgent***

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#308]
Background computation is broken with latest playbase. 

How to teplicate:
1. Upload example data from UI. Remove some contrasts.
2. Run computation with at least celltype deconvolution
3. Console error output is below

```
calculating UMAP 3D...
[pgx.clusterGenes] done!
[pgx.computePGX] computing extra modules...
[pgx.computeExtra] setting libx.dir =/home/kwee/Playground/omicsplayground/libx
Error in intersect(extra, EXTRA.MODULES) : 
  object 'EXTRA.MODULES' not found
Calls: <Anonymous> ... intersect -> intersect.default -> <Anonymous> -> as.vector
Execution halted
```

**Comment by ivokwee** [comment]
I think the error is in playbase, obviously....

**Comment by mauromiguelm** [comment]
I computed a new pgx with latest playbase and latest OPG and it worked well, was there a specific condition that crashed the computing?

**Comment by mauromiguelm** [comment]
I was able to reproduce the same error with example-data (latest playbase and opg), going to have a look at it

**Comment by mauromiguelm** [comment]
this can be fixed by declaring `EXTRA.MODULES` as the code below, I saw you made changes on computeExtra @ivokwee, so I will not merge my changes!

pgx.computeExtra <- function(ngs, EXTRA.MODULES, lib.dir, sigdb=NULL) {

    timings <- c()
    libx.dir <- paste0(sub("/$","",lib.dir),'x')  ## ../libx yikes....
    # message("[pgx.computeExtra] setting libx.dir =",libx.dir)

    extra = c("meta.go","deconv","infer","drugs", ## "graph", 
            "connectivity","wordcloud")

    extra <- intersect(extra, EXTRA.MODULES)

**Comment by ivokwee** [comment]
please update playbase. There was a redundant alias with compute_extra() and pgx.computeExtra() with the undefined EXTRA.MODULES. It's now hardcoded in the function parameters and I remove pgx.computeExtra (in favor of future snake_case naming). Should be solved now please check before closing this issue.

**Comment by ivokwee** [comment]
NAMESPACE updated to reflect deletion of pgx.computeExtra. removed extra intersect() https://github.com/bigomics/playbase/commit/94d7321b4c9c0684ff6cc0f6e0a4e88b317f1ba5 . please pull before install. 

Seems ok now. closing issue.
