### ISSUE TITLE
Input gene ID format

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#310]
I noticed that nowhere in the documentation we specified in what format the gene or protein ID should be provided to the platform. I think this should be clarified and added to the documentation. I know HUGO and Ensembl are supported, for example, but what about UNIPROT ID? What about Entrez?

**Comment by mauromiguelm** [comment]
This is a very valid point, we need a reliable source of information where we can check these details! We could reformat the text-based tutorial below, I really like it and it has great content already. I could do that when I re-do the upload module to accept new species and features.

https://omicsplayground.readthedocs.io/en/latest/

**Comment by ivokwee** [comment]
the current valid conversions are for human, mouse and rat for the following IDs, see [playbase/pgx-functions.R [line 302+]](https://github.com/bigomics/playbase/blob/371961d64fbf3f3577c671fdd5cc7c64d196fb8f/R/pgx-functions.R#L301-L329). @Axel, please update in documentation.

```
            "human.ensembl" = unlist(as.list(org.Hs.eg.db::org.Hs.egENSEMBL)),
            "human.ensemblTRANS" = unlist(as.list(org.Hs.eg.db::org.Hs.egENSEMBLTRANS)),
            #"human.unigene" = unlist(as.list(org.Hs.egUNIGENE)),
            "human.refseq"  = unlist(as.list(org.Hs.eg.db::org.Hs.egREFSEQ)),
            "human.accnum"  = unlist(as.list(org.Hs.eg.db::org.Hs.egACCNUM)),
            "human.uniprot" = unlist(as.list(org.Hs.eg.db::org.Hs.egUNIPROT)),
            "human.symbol"  = unlist(as.list(org.Hs.eg.db::org.Hs.egSYMBOL))
            )
```

**Comment by ivokwee** [comment]
not sure if we convert Entrez correctly, although it is easy because it is the intermediate format for conversion.

**Comment by ivokwee** [comment]
Why reopen? It's just a question. Please update docs and close.
