### ISSUE TITLE
 set the Fold Change in differential analysis instead of logFC

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#312]
Expansion suggested by the user Shabab on google Forum:

I wish we could set the Fold Change in differential analysis instead of logFC as there are limited options in the menu, making it hard to choose the right cutoff for next steps. 
Working with TMT proteomics, and the platform for generating proteomics data, our group usually sets the cutoff at |FC|>1.2 but this is not obviously possible even in the Beta version. converting the LogFC values, we have the following options in the platform:

log FC        FC
  1                2
0.5              1.41421
0.2              1.1487
0.1              1.07177

To make the package more versatile, can you please add 0.263034 which represents log 1.2 to current logFC values? or add a continuous scroll bar somewhere in the options? 
Cheers,
Shahab

**Comment by ivokwee** [comment]
No we will not add 0.263034 as threshold. It looks weird such a threshold. We could consider a slider value for continuous value but I like predefined values for simplicity. I told Shahab he can export to Excel and threshold there. 

Closing this issue.
