### ISSUE TITLE
User defined gene sets

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#316]
Users would like to upload userdefined genesets.

**Comment by mauromiguelm** [comment]
I had to do quite some changes on gene set functions in order to make wgcna work, I learned quite a bit about how the app handles gene sets. 

I could combine to the task of reformulating uploading to alow multi-species and multi-features

**Comment by ivokwee** [comment]
Seems a duplicate of issue #93

BTW @mauro  don't combine task.... please keep them small and independent...
