### ISSUE TITLE
margin left and right of base and ggplot should dissapear

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#319]
we have a big gap between the edge of the card and the plot.

**Comment by mauromiguelm** [comment]
Plots with problems after margin correction:

Expression > Diff exp > plot > volcano plot
Expression > Diff exp > plot > Bland-Altman (MA) plot
Expression > Diff exp > plot > Gene in contrasts
Enrichment > Pathway analysis > Reactome > Activation matrix
Enrichment > Pathway analysis > GO graph > Activation matrix

**Comment by ivokwee** [comment]
OK. removing high priority. Remaining can be done later.

**Comment by ivokwee** [comment]
closing.
