### ISSUE TITLE
empty plot at clustering after filter samples ***HIGH PRIORITY***

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#322]
Empty plots after filtering samples with example data. NB. I turned off bigloaders to see if it was related to that. It seems not.

1. load example data
2. clustering tab
3. active filter samples: cluster=c1 and cluster=c2
4. Emtpy plots

![image](https://user-images.githubusercontent.com/19613146/233064959-4c8d0b53-c53d-476c-8797-b5fdf5edac32.png)

**Comment by ivokwee** [comment]
Actually also same problem at beta.playground.bigomics.ch (Omics Playground v3.0-RC.230413).  Filter samples: cluster=c1 and cluster=c2

V2 seems also ok (see below)

![image](https://user-images.githubusercontent.com/19613146/233067997-a8676ad4-ca95-4df1-8e6c-dac3db00fba5.png)
![image](https://user-images.githubusercontent.com/19613146/233068131-15056f79-2621-4212-a625-8cd9974ef17f.png)

**Comment by ESCRI11** [comment]
@ivokwee Cannot reproduce locally with latest `master` branch and latest `playbase` installed.

![image](https://user-images.githubusercontent.com/10220503/233080129-3e144645-1b03-4d73-a6fe-b9c897fec7f2.png)

**Comment by ivokwee** [comment]
I did a fresh git clone from omicsplayground and playbase. Same problem. On the console I see this warning:
```
Warning in processWidget(instance) :
  renderDataTable ignores ... arguments when expr yields a datatable object; see ?renderDataTable
```

**Comment by ivokwee** [comment]
Strange. This bug is not present on my laptop. But both me and Mauro experienced this yesterday. I am going to update all Ubuntu packages (sudo apt update && apt upgrade)  and R/Biocondutor, please do the same:

```
sudo apt update && sudo apt upgrade

upgrade.packages(ask=FALSE)
BiocManager::install()

```

**Comment by ivokwee** [comment]
Screencast below illustrates the error. 

[Screencast reactivity-error 04-20-2023 10:56:33 AM.webm](https://user-images.githubusercontent.com/19613146/233315081-c8cd658e-6867-490e-beaf-b993ac7ca0c6.webm)

**Comment by ivokwee** [comment]
Also this seems to happen depending on the computer. In the docker build (luckily...) this problem seems not to exists. On my desktop still having this problem, laptop not. I updated both to latest package versions (linux, R/Bioc). It would be good to report the versions we use for OS and R/Bioc if you encounter (or not have) this problem. This is a pretty important thing to solve but luckily the docker seems to work fine.

**Comment by mauromiguelm** [comment]
**The problem is inside this commit:**
commit 351988a0d41e15405d4a68f12783dafe6584affe
Author: Ivo Kwee <[ivo.kwee@gmail.com](mailto:ivo.kwee@gmail.com)>
Date:   Thu Apr 13 17:54:48 2023 +0200
    ivo edits

**Comment by ivokwee** [comment]
I found the "error". Me and Mauro were still running an older version of bigLoaders. After updating this error disappeared. Please update your bigLoaders if you encounter this error.
