### ISSUE TITLE
Invalid menu items when switching dataset

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#336]
Problem:  when switching from a full data sets (i.e. with all options computed) to a reduced dataset (i.e. without the extra computation options), the menu items 'signature/similar experiments', 'enrichment/drug connectivity', 'wordcloud' and 'cell profiling' should be hidden automatically. 

Solution: in server.R we should trigger the hide/show of menuitems properly. Check if it is triggered at dataset change. Check if the checks are correct.

**Comment by mauromiguelm** [comment]
@ivokwee did you check this issue with John? If not I will work on it in the next days

**Comment by ivokwee** [comment]
This is not a John issue. But the fields inside the pgx should trigger correctly which tabs to show or hide. I guess this is not correctly done when you change to a pgx with less fields.

**Comment by ivokwee** [comment]
I am on it... The bug is easily repeatable if you first load a fully computed dataset (example data, all computation options), and then a "smaller" dataset (example data, no extra computation options), and then click for example "drug connectivity" (see below). A pgx file without say "drug connectivity" results should not show the menu item. Or should we "disable" it by greying it out?

![image](https://user-images.githubusercontent.com/19613146/236879426-966303a9-6941-4e09-85f0-30be73e6579a.png)

**Comment by ivokwee** [comment]
fixed. corrected the checks for hide/show in tabRequire and bigdash.toggleTab. See commit 56ce4ff35e486b1449f486301f4d401e98c411bd
