### ISSUE TITLE
Reduce/remove/replace large R packages from docker 

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#340]
If we look at the installed R packages in the docker, they occupy about 4GB space. You can show the largest packages by using 

`du -h -d1 /usr/local/lib/R/site-library/ | sort -h`

inside the docker container. Ouput is shown below. Most large packages are species annotation. We use them only for converting probes to gene names at loading, so we could replace them with a smaller version by only extracting the necessary lookup table. Instead of installing the whole species annotation package, we would need to save just the probe conversion table. Should be much lighter. It seems this could easily reduce the docker size by 2-3 GB.

```
47M	/usr/local/lib/R/site-library/TxDb.Hsapiens.UCSC.hg19.knownGene
50M	/usr/local/lib/R/site-library/Rhdf5lib
59M	/usr/local/lib/R/site-library/RSpectra
59M	/usr/local/lib/R/site-library/TxDb.Mmusculus.UCSC.mm10.knownGene
70M	/usr/local/lib/R/site-library/SBGNview.data
84M	/usr/local/lib/R/site-library/GO.db
95M	/usr/local/lib/R/site-library/EnsDb.Rnorvegicus.v79
96M	/usr/local/lib/R/site-library/xgboost
100M	/usr/local/lib/R/site-library/TCGAbiolinks
156M	/usr/local/lib/R/site-library/BH
174M	/usr/local/lib/R/site-library/torch
202M	/usr/local/lib/R/site-library/EnsDb.Mmusculus.v79
219M	/usr/local/lib/R/site-library/playdata
244M	/usr/local/lib/R/site-library/org.Rn.eg.db
294M	/usr/local/lib/R/site-library/org.Mm.eg.db
308M	/usr/local/lib/R/site-library/org.Hs.eg.db
333M	/usr/local/lib/R/site-library/EnsDb.Hsapiens.v86
4.0G	/usr/local/lib/R/site-library/
```

**Comment by ivokwee** [comment]
Having three annotation db for human:  EnsDb.Hsapiens.v86, TxDb.Hsapiens.UCSC.hg19.knownGene, and org.Hs.eg.db might be redundant and (maybe?) we can use just one. But this needs a further look whether we can use just one.

**Comment by mauromiguelm** [comment]
since @phisanti is leading the multi-species, this can solve this ticket

**Comment by phisanti** [comment]
I will likely have a workable version of `playbase` with full `biomaRt` integration. From there, I can do some dependency cleaning.

**Comment by ivokwee** [comment]
Closing  stale issue.
