### ISSUE TITLE
Welcome tab has no bottom border

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#361]
Welcome tab has no bottom border after loading dataset and coming to dataview page

<img width="1262" alt="Screen Shot 2023-05-08 at 3 58 35 PM" src="https://user-images.githubusercontent.com/13004360/236843888-1337f3ba-a646-475b-96d6-df45e6dd8e0d.png">

**Comment by ivokwee** [comment]
Actually the welcome tab (better: menu item) should be always hidden. The company logo works as the button to go to the welcome page. Not sure why we see suddenly the welcome tab, it was always hidden.

**Comment by ESCRI11** [comment]
Got it, hidden the welcome tab from the menu directly on master https://github.com/bigomics/omicsplayground/commit/e3b2583563e65d3000d30c395efcd879be4f16a2
