### ISSUE TITLE
The option of visualising all gene sets is missing in Gene Set UMAP in V3

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#367]
I just noticed that the Gene set UMAP plot no longer displays all databases when highlighting an area. Would it be possible to add the options to do so again, rather than being forced to select a specific database like GO or KEGG? Basically having an "all" option, as is the case for the Enerichment plots?

**Comment by ivokwee** [comment]
Fixed. Key of plotly selection was wrong (see fix in playbase). Add checkbox for full table or filtered. See commit 58617db1bdcc337562e66d7a87c9a652235fec3b
