### ISSUE TITLE
downloaded png of plot is empty

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#368]
When I load an example dataset then try to download the Gene expression plot as png, I either get a weird txt file or I get a plot.png that is 0 bytes is size and cant be opened.

This is the only relevant feedback I get:

<img width="684" alt="Screen Shot 2023-05-09 at 11 32 05 AM" src="https://user-images.githubusercontent.com/13004360/237055817-8f6f788a-38c6-4043-bf24-58ab385e462c.png">

**Comment by ESCRI11** [comment]
I assume you are having this problem locally. For me it works OK locally, you may be missing the required system packages that take care of downloading the plots. Take a look here https://github.com/bigomics/omicsplayground/wiki/%60recticulate%60-setup
