### ISSUE TITLE
zoom in and out of plotly plots with scroll

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#371]
zoom in and out of plotly plots with mouse scroll, instead of selecting an area with click and drag

@ivokwee?

**Comment by ivokwee** [comment]
Is that possible? But then simultaneously panning is also important for selecting the area where to zoom

**Comment by mauromiguelm** [comment]
should be able with a few tweaks, its possible in plotly python: https://plotly.com/python/configuration-options/

imo significantly improve UX
