### ISSUE TITLE
include input options when downloading zip file on loading datasets

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#373]
It would be nice to extract the parameters that are provided to pgx compute, so we can load these "settings" together with the csv files.

**Comment by ivokwee** [comment]
It would be good to record the parameters *inside* the pgx as reference. We could allow a settings.csv file for computation settings. But to be honest, not sure how many users would use this. Perhaps those as service provider with certain preferred settings. I am going to close this, please reopen if we get a client request of this kind.
