### ISSUE TITLE
zoom in doesn't really work on draggable/sortable figures

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#374]
When I try to zoom in on a figure that is part of a draggable/sortable-js row, it really doesn't work or at least looks really weird because it makes me drag the row while also trying to zoom in. The figure below shows me just trying to zoom in on the middle figure. I think the best solution would be to somehow only make the sortable-js stuff work if you're clicking outside of the figures, like only in the headers. If this doesn't work, then removing sortable-js would be my recommendation.

Side issue: the mouse icon should change to the drag type to let people know that a row/figure is draggable/sortable. Otherwise it's just like at best a hidden functionality and at worst an unintended functionality that will confuse the user because the mouse hasn't changed to let them know something is draggable as is convention.

<img width="1440" alt="Screen Shot 2023-05-12 at 11 46 29 AM" src="https://github.com/bigomics/omicsplayground/assets/13004360/2bbbe974-0378-4898-81e0-832e9726ce8c">

**Comment by mauromiguelm** [comment]
Agree, we should remove the draggable elements, I can do that

**Comment by mauromiguelm** [comment]
@ivokwee I commited to master since this is a small change. We can revisit sortable in the future with a better solution.

Let me know otherwise.

M

**Comment by ivokwee** [comment]
OK. I did see did problem before. It's a shame because the draggable thing was nice.
