### ISSUE TITLE
plotly plots don't automatically resize after closing blue info bar

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#375]
When closing the blue info bar located just under the tab headers on a page, the plotly plots don't automatically resize. Not sure if there needs to be a trigger added. Example below of how it looks right after I close the blue bar. You can see there is a bunch of extra vertical white space under each plot because it somehow hasn't registered that the plots have more vertical space to expand now that the blue bar is closed.

<img width="1199" alt="Screen Shot 2023-05-12 at 1 03 13 PM" src="https://github.com/bigomics/omicsplayground/assets/13004360/ddfbc2b5-cec3-4206-b44c-d86c4221f39e">

**Comment by ivokwee** [comment]
@ncullen93  Yes. Sometimes plotly needs a little bit of help. Probably if you change the window a bit it will force redraw. In www/temp.js we use 	and explicit call to JS `$(window).resize();` when needed. It's an ugly solution. We might want to bind the window.resize to the close button of the bs_alert box.
