### ISSUE TITLE
wrong vertical sizing of contrasts tab on upload page

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#376]
Somehow the contrasts tab of the upload page has a larger vertical page size than other tabs. This makes it so the little monster is no longer fixed the bottom left of the page. See example pictures of the two tabs. Perhaps this relates to the blue info bar making the page bigger and the contrasts UI not resizing / shrinking like other pages' UI given that it's a bit different.

<img width="1440" alt="Screen Shot 2023-05-12 at 1 15 45 PM" src="https://github.com/bigomics/omicsplayground/assets/13004360/5584c57a-f268-4849-884b-9f803efd270f">

<img width="1440" alt="Screen Shot 2023-05-12 at 1 15 36 PM" src="https://github.com/bigomics/omicsplayground/assets/13004360/498fed1b-8881-4cb2-ba5d-87eccc0049ec">

**Comment by mauromiguelm** [comment]
confirmed, I did some unrelated tests and found the same issue. I guess we can reduce the vertical height of the contrast table, should be an easy fix - hopefully
