### ISSUE TITLE
make tabpanel labels reactive so they always remain one line

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#377]
Currently, tab labels are not reactive -- i.e., the font size does not decrease with smaller screens. This makes it so tab label headers can span multiple lines, as the right-side panel in the example figure below shows (this is how it looks on my screen at 100% / normal zoom). It would be nice if there was a way to make the tab label header resize to always remain one line.

Alternatively, we can just rename those tab labels so that they aren't as long :)

<img width="1053" alt="Screen Shot 2023-05-12 at 1 26 54 PM" src="https://github.com/bigomics/omicsplayground/assets/13004360/0740156d-fdb3-4904-9174-d32e6d760102">

Actually, the same thing happens with plot titles, as shown below for the third figure from the left:

<img width="1045" alt="Screen Shot 2023-05-12 at 1 31 30 PM" src="https://github.com/bigomics/omicsplayground/assets/13004360/da388c27-1ad6-49a7-9a17-3013cfda2b34">

**Comment by ivokwee** [comment]
Noted. Solution? we could make the font size reactive? All in favor to shorten labels when possible. Other possiblity is that the CSS maybe can truncate long lines. This is done for the captions here https://github.com/bigomics/omicsplayground/blob/0bde5cb32041335b964642b4ddbd342f66f5848c/scss/components/_all.scss#L132-L136
