### ISSUE TITLE
dataset options icon cutoff on data load page

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#383]
On my computer, the dataset options icon (three vertical dots) is cutoff. It is absolutely essential that this icon is visible on every screen at 100% zoom. There are a few options to solve this -- (1) increase width of the data load table and decrease width of the tsne table, (2) decrease font of the table, (3) move the options icon to the left side of the row instead of at the end (right side)

Example picture below:

<img width="1047" alt="Screen Shot 2023-05-12 at 8 01 34 PM" src="https://github.com/bigomics/omicsplayground/assets/13004360/af3780cf-0aea-45cd-9934-28e4ce4d4a56">

**Comment by ESCRI11** [comment]
@ncullen93 I am not a fan of options 1 and 2. Personally, I would exchange the rownames (I do not think they have any relevant meaning in this table) for the three dots:
![image](https://github.com/bigomics/omicsplayground/assets/10220503/15a88af9-ed3f-4e3b-80a4-262433612815)
If that sounds good to you I will quickly put together the PR with the changes.

**Comment by ESCRI11** [comment]
There you go! :D #390
