### ISSUE TITLE
make user profile changes (e.g. enable beta) persist across sessions

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#384]
Right now, I'm just guessing from the code that any profile changes would not persist across user sessions. The only real profile change we have now is to enable beta features, but we will add more soon. I think users would expect these changes to persist across sessions, and having to go and change profile settings every time you use the app would be quite cumbersome in any case. 

The only way to make these changes persist is to store them in a database -- either hosted or stored locally on the server -- or if we are against that then they would be stored in a file in the user's directory like we do with pgx files.

**Comment by ivokwee** [comment]
Noted. We could generalize the OPTIONS file, or create a new settings file. Not high priority issue but useful. This links perhaps with the idea to make a user OPTIONS file that can override the app/R/OPTIONS.
