### ISSUE TITLE
remove duplicate probe2symbol call for counts.csv upload if possible

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#386]
Currently, the time between uploading of counts.csv files and display of the data figures on the upload page is SO long -- likely because of these lines in `upload_server.R`:

```
      if ("counts.csv" %in% names(matlist)) {
        ## Convert to gene names (need for biological effects)
        dbg("[upload_files] converting probe names to symbols...")
        X0 <- matlist[["counts.csv"]]
        pp <- rownames(X0)
        rownames(X0) <- playbase::probe2symbol(pp)
        sel <- !(rownames(X0) %in% c(NA, "", "NA"))
        X0 <- X0[sel, ]
        xx <- tapply(1:nrow(X0), rownames(X0), function(i) colSums(X0[i, , drop = FALSE]))
        X0 <- do.call(rbind, xx)
        dbg("[upload_files] ...done!")
        matlist[["counts.csv"]] <- X0
      }
```

But these lines happen already as a processing step when the pgx file is computed. If these lines aren't necessary for the data preview plots (I don't think they are) then there is no reason to have it here before the user decides to compute the pgx object -- it just slows things down a ton.

Just removing those lines makes the time from upload to figure rendering drop from like 15 seconds to <1 second. Data upload should be as quick as possible by moving all the computation to the compute pgx functions.

**Comment by ivokwee** [comment]
For the batch correction based on mitochondrial content, ribosomal, or gender, we need to know the gene symbols. Because the batch correction is done before pgxcompute. for the moment we need it. A solution could be to skip it if the user does not want to do batch correction, and do the conversion if batch correction is on.

**Comment by ivokwee** [comment]
Done in PR "Move probe2symbol #429"
