### ISSUE TITLE
All YouTube modals should show xl large screen video + adding alert box in each module.

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#393]
All YouTube help modals should show just the video without text in xl screen. See example Load Dataset below. The text can be moved (with editing) into an bootstrap alertbox.

![image](https://github.com/bigomics/omicsplayground/assets/19613146/c91ddd62-24bf-4966-9841-c28711eaf1ef)

**Comment by ivokwee** [comment]
setting this to high priority. Not breaking code but visible to user, so I find this important to do asap.

**Comment by mauromiguelm** [comment]
complementing Xavier: 
- we have a few boards where the modals have important information to understand certain plots, should we maybe move that to plot module info.text?
- Some boards do not have video (correlation analysis, find biomarker, single cell board...). We need to coordinate to create these videos

**Comment by ivokwee** [comment]
stale issue. archiving
