### ISSUE TITLE
GO score table not working: GO graph do not update any plot

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#396]
identified it while updating gmt's, working on it

**Comment by ivokwee** [comment]
Perhaps the GO graph needs all GO genesets (I dont remember but I guess it does), and they got filtered out by your thresholds. If so, you should not filter out any GO genesets, even if they are larger than 400-500. Those are probably the higher level terms.

**Comment by mauromiguelm** [comment]
Hi Ivo, GO is working, I did not change how GO genesets are passed. This issue was a mistake due to playbase not being updated on my end.

Best,
M
