### ISSUE TITLE
cluster features UMAP broken coloring

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#403]
The gene signatures plot (right hand side) all show grey. 

![image](https://github.com/bigomics/omicsplayground/assets/19613146/27ae1ab2-c289-424e-809a-4a5f713b2380)

**Comment by ESCRI11** [comment]
I can reproduce it on Docker `latest` but not on `main` branch. Any idea?

**Comment by ESCRI11** [comment]
OK I had old version of `playbase`. Now I can reproduce it locally. Working on it.
