### ISSUE TITLE
Hidden sidebar tabs still show their horizontal rule

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#406]
When tabs are hidden (e.g., beta tabs), the grey horizontal line under (or above? I think under) the tab is not hidden. This leads to thicker horizontal lines in the sections with hidden tabs. See example below under the "Find biomarkers" tab, that grey line should not be so big. This also happens in the Clustering section under "Features"

<img width="193" alt="Screen Shot 2023-05-23 at 9 58 53 AM" src="https://github.com/bigomics/omicsplayground/assets/13004360/d4f35c0b-5798-4efe-9e7f-967e924f429b">

**Comment by ESCRI11** [comment]
Same as #342 closing that one and assigning myself.
