### ISSUE TITLE
card footer size not consistent

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#418]
For some reason the card footers heights are all over the place now. Perhaps some relevant CSS got deleted/moved??

![image](https://github.com/bigomics/omicsplayground/assets/19613146/440c75dc-8284-4404-80c5-e9902ee7cfcd)

![image](https://github.com/bigomics/omicsplayground/assets/19613146/98ca8888-6e03-42c6-b0c1-6da808ecf2a1)

**Comment by mauromiguelm** [comment]
Cannot reproduce on latest packages, consider updating bigdash, someone pushed changes a few days ago

<img width="1136" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/14e629aa-465f-4815-98a7-534d5e028a73">

**Comment by mauromiguelm** [comment]
No new report, closing
