### ISSUE TITLE
Gene KO L1000 database missing in V3.11 and V3 (3.0.RC6.230.426)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#421]
When using V3.11 with a new dataset I recently prepared from input files, I could no longer access the L1000 gene KO database. Has it been removed? I think it should be re-instated if so.

![image](https://github.com/bigomics/omicsplayground/assets/85561624/fdd78183-7171-4544-8a41-af49c180fb9a)

**Comment by mauromiguelm** [comment]
nice catch, I will find out why it got kicked out.

Its possible I kicked it out because the database got so big, that it crowded all other results. I will investigate

**Comment by mauromiguelm** [comment]
this is drug connecitivity map

**Comment by AxelBigOmics** [comment]
I can confirm that the Gene KO database is also missing from version 3.0.RC6.230.426 (latest release):

![image](https://github.com/bigomics/omicsplayground/assets/85561624/079a7d72-4417-483f-9deb-2f33b97e61c5)

**Comment by mauromiguelm** [comment]
update: this is unrelated to genesets, the inputs for drug connectivity is libx... will investigate why

**Comment by mauromiguelm** [comment]
update: there are more problems in the drug connectivity board that's crashing in some instances (eg. reactivity outside reactive container), going to fix and do the PR
