### ISSUE TITLE
Cannot compare Human and mouse datasets under "signatures in V3.11 and V3 (3.0.RC6.230.426)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#423]
Under "Signatures->compare datasets (beta)", if I compare a human and mouse genomes, I get no gene names showing up except the ones consisting of a single capital letter. This is an issues carried on from V2, related to the capitalisation of Human but not mouse HUGO acronyms:

![image](https://github.com/bigomics/omicsplayground/assets/85561624/ebfabbc3-3891-4870-948c-595b1506f3ff)

**Comment by ESCRI11** [comment]
@mauromiguelm This is probably related (and can be fixed using a similar approach) as this: https://github.com/bigomics/omicsplayground/pull/455

**Comment by mauromiguelm** [comment]
update: the problem happens when we have a mouse dataset as dataset1 and human as dataset2.. investigating
