### ISSUE TITLE
Dataview "error" message  under GTEX tissue expression for non-coding genes (V3)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#424]
Under "Dataview",  some genes (e.g. pseudogenes) that have no entries in GTEX give an error message. While this is the correct behaviour, it gives the impression that the platform is broken. Can the missing data be handled differently (e.g. a message indicating that no data is available?):

![image](https://github.com/bigomics/omicsplayground/assets/85561624/c6e9ce97-1bce-4c4e-a2d4-56dd6215ebe9)

**Comment by ESCRI11** [comment]
@ivokwee Is this solved? If not, which dataset can I use to reproduce it? Easy to solve with the `validate` shiny function

**Comment by phisanti** [comment]
Which dataset did you use to trigger the bug?

**Comment by ivokwee** [comment]
archiving as stale.
