### ISSUE TITLE
Prize-collecting Steiner Forest looks not enabled yet in V3.11

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#425]
New feature PCSF looks like it is not enabled yet in V3.11:

![image](https://github.com/bigomics/omicsplayground/assets/85561624/96e51a6a-a998-42e3-9890-e5ef1b91cf10)

**Comment by ivokwee** [comment]
working on it. should be fixed in next docker build.

**Comment by ESCRI11** [comment]
Latest docker is fixed
