### ISSUE TITLE
Wikipathways plots have truncated text in V3 (3.0.RC6.230.426)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#428]
I noticed this bug several times: The platform seems to "chomp" the first letter in the Wikipathways plots. Interestingly, it seems to always affect text written in a certain format (see below).

![image](https://github.com/bigomics/omicsplayground/assets/85561624/8ceb7faa-5865-4b01-aaa2-204c032053c8)
![image](https://github.com/bigomics/omicsplayground/assets/85561624/24e1dff3-109d-44bc-bb7b-3f6c8f968b6c)
![image](https://github.com/bigomics/omicsplayground/assets/85561624/0886bffa-360c-4da6-a758-e04d3de3585c)

**Comment by ivokwee** [comment]
Again. Not easy because we download the SVG files ready like this. @mauromiguelm if you want to hack into the SVG or find other SVG files, be my guest.
