### ISSUE TITLE
upload data: improve filtering definitions and report excluded data

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#458]
- Make more clear which genes are filtered out
- Output this list with filtered genes and place in dataview > resources

[Note: this was a request from user as they often get asked why a certain favorite gene cannot be found in the results on OPG. So she needed too often check manually why a gene was filtered out.]

**Comment by mauromiguelm** [comment]
irrelevant for now, needs further discussion

**Comment by mauromiguelm** [comment]
reopened as this will increase transparency. In dataview > resources, we could add the genes removed, the reasons, along with other related dataset statistics.

**Comment by ivokwee** [comment]
There is already a 'slot' in pgx with the name "filtered"  (pgx$filtered) which contains the names of genes/features that are filtered out by the low.expressed filter. We may add more filter results like "non-coding" or "not known gene" etc. This can be used to report. 

The other thing is that pgx$counts generally consists of non-filtered values close to the original input matrix. I think complete zero rows are deleted to save memory but all other genes are retained. It is the pgx$X (log transformed, normalized) matrix that is filtered (thus smaller) for either statistical reasons or not interesting.

**Comment by ivokwee** [comment]
archiving as stale issue.
