### ISSUE TITLE
download pop-up dissapear

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#459]
- on the modal pop-up containing the download options for each plot, sometimes it dissapears when you click on it.. you need to use the tab which is inconvenient

see user feedback

**Comment by mauromiguelm** [comment]
never happened to me

**Comment by ESCRI11** [comment]
I understand they refer to this old bug, if that is the case, it is already fixed. https://github.com/bigomics/omicsplayground/issues/398

**Comment by ivokwee** [comment]
Should have been fixed. See also #402
