### ISSUE TITLE
Bootstrap tooltip does not dissapear

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#467]
See user feedback

<img width="98" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/c075ed2a-3dca-4afb-89f5-84784f6822cc">

**Comment by ivokwee** [comment]
This is not plotly, but the tooltips. This happened a lot in v2 but I actually didn't see such a thing in v3, until now. Previously in v2, the tooltip stayed even when chainging tabs/pages. The only think was to go back to the original tab/page and hover and leave over the tooltip for it to dissappear. Before we used, I think, bsTooltip, which gave often this problem. John then replaced it with the standard BS5 tooltip and generally the problem had gone.
