### ISSUE TITLE
Dead links in OPG

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#468]
on geneset enrichment, some of the links are directing to "gene set not found" on GSEA website

<img width="318" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/6ddc27c8-c307-4727-b6a1-082733d30617">

see user feedback

**Comment by mauromiguelm** [comment]
I agree, we could have a report form for when people find deadlinks in the table itself... there will be future challenges as API changes, websites down, renaming of genesets, etc...

so we need to activelly fix these things, as it seems they are important to the users!

**Comment by mauromiguelm** [comment]
would be useful for bugs and suggestions in general, we can discuss with Ivo and see how to move forward. I would love see this implemented.

**Comment by mauromiguelm** [comment]
I will reopen this, as we might have a solution that applies to many cases:

One solution would be for the user to be able to report broken links (or plots, tables) directly in the plot or table. What do you think?

User reply: Yes that would be a nice way implement noting dead links.

Should we use this approach @ivokwee?

**Comment by mauromiguelm** [comment]
I think that would be great, both for suggestions and issues. For example, certain datasets might create plot problems, and would be nice if the user could report to us.

Let's get the ok from @ivokwee as this is a big change.

**Comment by ivokwee** [comment]
I don't like the reporting thing. Before that we should investigate why the links are not working. You do not need to check 2000 links manually, you can create a simple loop and do a curl to check them all. In any case, if you get them from external DB there must be a link.

**Comment by ivokwee** [comment]
I don't like asking users to actively debug dead links. Looks like we ship broken stuff. Better disable the link. Again, we could just test each link in a loop if needed.

**Comment by mauromiguelm** [comment]
correct, the link works, but the database cannot find the entry, as image below, and returns a standard page. I dont see any easy solution other than Beautiful Soup or some report button.

> on geneset enrichment, some of the links are directing to "gene set not found" on GSEA website
> 
> <img alt="image" width="318" src="https://user-images.githubusercontent.com/28757711/245447430-6ddc27c8-c307-4727-b6a1-082733d30617.png">
> see user feedback

**Comment by ivokwee** [comment]
So you can grep on 'geneset not found'... But again I think we should find out why a certain gene set is not found: any extra spaces? Newline? Non UTF8 chars? Can you give me an example of a geneset that is not there?

**Comment by ESCRI11** [comment]
Did some research, looks like all C5 genesets links are broken, have not found any other broken link on different genesets.
