### ISSUE TITLE
Plot is clipped

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#469]
Some plots in Differential expression > top genes > expression of top differentially expressed genes have their margins set incorrectly and the title is being clipped by the card border

see user feedback

**Comment by ivokwee** [comment]
I believe this has been fixed in the mean time. See figures. Closing issue.

![image](https://github.com/bigomics/omicsplayground/assets/19613146/c2c08b7c-d192-480d-9f1b-1245cdd9f6f6)
![image](https://github.com/bigomics/omicsplayground/assets/19613146/81652daa-9d17-47dd-8001-6e6aec4e23bf)
