### ISSUE TITLE
Some plots are not being populated with points

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#471]
Volcano plots for all contrasts
<img width="98" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/578fddd8-ec8c-4872-b4f2-dc757611419b">

see user feedback

**Comment by ivokwee** [comment]
I have not seen this error. Perhaps ask the user if they still have this error.

**Comment by ivokwee** [comment]
let's close until reconfirmed.
