### ISSUE TITLE
Feature request: interactive compare foldchange plot under the "Compare dataset" tab

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#472]
Hi,

I wanted to suggest making the foldchange plot interactive, so that I can select a group of genes on the plot and have a list with the IDs appearing (similar to what is currently done with the "Gene UMAP" plot).
Adding an example of the plot in question below for reference. in this case I'd like to "lasso" the genes around IL1RL1 to find out which ones are upregulated in one of the pairwise comparisons but downregulated in the other, particularly when comparing datasets of different origins.

![image](https://github.com/bigomics/omicsplayground/assets/85561624/eb98409e-af83-46b2-aa1d-3030074eccf0)

**Comment by phisanti** [comment]
I have just implemented the interactive version in the branch [interactive_plot_#472](https://github.com/bigomics/omicsplayground/tree/interactive_plot_%23472). Maybe, @mauromiguelm or @ivokwee can test it, and if works properly, we merge. Also, if the change is approved, I think I could manage to make the other plots in the compare tab interactive.
