### ISSUE TITLE
Mouse maybe general datasets: correlation analysis not working when contrasts are equal

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#481]
GSE194417_mouse

<img width="986" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/ce6485d6-3db9-4f14-852f-84635d32d84a">

**NOTE:** The two contrasts have the SAME enriched genes, that is likely crashing the module.

**Comment by ivokwee** [comment]
You should say "same enriched genes" that's for gene lists. better is to say: same fold-change (logFC). It that what you mean?

**Comment by ivokwee** [comment]
Correct diagnosis. Confirmed. Removed offending lines. It should have been set correctly in the loop aboved. Vector to matrix casting is done in loop.
