### ISSUE TITLE
The modal should be different for uploading a pgx file versus a newly computed pgx file

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#497]
The modal looks the same when you upload a pgx file and when a pgx file has finished being computed. An enhancement might potentially be to have separate messages and/or options between these two scenarios. 

This issue is opened to take suggestions on how those modals should differ. It can be closed when we either decide on what the difference should be and implement it, or if we decide that the modals are fine as they are.

<img width="433" alt="Screen Shot 2023-06-19 at 3 47 24 PM" src="https://github.com/bigomics/omicsplayground/assets/13004360/7e2c2c4c-fdd2-4c42-86d6-0253317368f1">

**Comment by ivokwee** [comment]
Solved in PR https://github.com/bigomics/omicsplayground/pull/595 . Closing issue.
