### ISSUE TITLE
settings bar is not visible in firefox (also on the trial version). 

### ISSUE THREAD

**Issue by ShaliniPandurangan** [bigomics/omicsplayground#498]
This is the webpage on chrome browser where the setting bar can be seen
![Screenshot from 2023-06-19 16-34-21](https://github.com/bigomics/omicsplayground/assets/56559132/d4867dcb-85c9-4765-b036-e1c96d2cad9e)
whereas, this is the screenshot of the webpage on firefox browser where settings bar is not visible
![Screenshot from 2023-06-19 16-34-28](https://github.com/bigomics/omicsplayground/assets/56559132/37edf810-cf78-4ca9-8a61-6fc491224745)

  

  

  
  
  
<details> <summary><strong>Session Info</strong></summary>
  
```r

```
</details>

**Comment by ESCRI11** [comment]
Could reproduce locally. Working into it

**Comment by ESCRI11** [comment]
Closing issue and following on #499
