### ISSUE TITLE
Multi/single-threading

### ISSUE THREAD

**Issue by bigomics** [bigomics/omicsplayground#5]
It seems like the app itself is single-thread.  Do you think that is a shiny-server limitation, or something inherent to the app itself?  I've got some horsepower to throw at it, would be great to speed it up.

[originally posted by email  by KT on 13.08.2020]

**Comment by bigomics** [comment]
The free version of R shiny-server is single-threaded and only the paid version is multi-threaded but costs a lot. That is why we opted for a dockerized deployment using shinyproxy. At least each docker gets a full separate thread/core. I guess if you really need multithreading, we need to adapt/test the code on the commercial version of shiny-server but currently we dont have that possibility

**Comment by ivokwee** [comment]
The Playground tries to precompute most of the heavy computations beforehand. So the slowness of the UI is often due to plotting. Some modules use online computation (like the biomarker module). which modules in particular do you find slow?
