### ISSUE TITLE
"Aw snap. Out of memory" error with Chrome

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#50]
This has been a common complain among Chrome users. After a while the Platform crashes with the error below.

This is a recent problem that started about 3-4 weeks ago. Previous versions of Chrome did not show this error.

![image](https://user-images.githubusercontent.com/85561624/154279140-a985bbe8-65fc-4eaa-90ae-739835d2baf4.png)

**Comment by stefanreifenberg** [comment]
So far i could not reproduce this error. I might need a larger dataset compared to the example data. Let me know if you can provide one a dataset for testing via dropbox or so.

**Comment by AxelBigOmics** [comment]
Hi Stefan,

The error does not appear with a specific task. What normally happens is that after 15-30 minutes the platform crashes with the "out of memory" error. Sometimes I can see the platform struggle to load the dataset into memory as well and there being long delays before I can click on any tab.

The dataset I normali experience this problem with is GSE162475, which you can download from our public dataset collection (https://public.bigomics.ch/app/omicsplayground_contrib).

**Comment by stefanreifenberg** [comment]
Hey Axel,

from your description it sounds like a memory leak. The app allocates more and more memory without clearing unneeded data from the memory, resulting in Chrome crashing at some point.

**Comment by AxelBigOmics** [comment]
Sounds about right...how can this problem be fixed? Or is it an issue with Chrome itself?

**Comment by stefanreifenberg** [comment]
The issue stems from the shiny app. We should implement garbage collection to get rid of obsolete data in the memory. 
Here is some information: https://bookdown.org/content/d1e53ac9-28ce-472f-bc2c-f499f18264a3/releasememory.html#use-gc

**Comment by AxelBigOmics** [comment]
Thanks for the explanation, Stefan. That is an important issue for some of our clients, so hopefully it can be fixed relatively easily (not a programmer myself btw, so no idea how long that can take).

**Comment by stefanreifenberg** [comment]
Good to know, i'll try to replicate the issue and start working on it

**Comment by ivokwee** [comment]
Not sure if garbage collection will do. Garbage collection will only clear the memory on the *server* side, and the error seems on the *browser* side. We saw this error especially with Chrome and got worse after the Windows 11 update. We don't see this problem on Linux or Mac.

**Comment by AxelBigOmics** [comment]
Just a quick update...I did not seem to experience the issue today. Will keep an eye on it. Maybe Chrome/Win11 fixed whatever the issue was? Or did any of you guys work your magic?

**Comment by stefanreifenberg** [comment]
Nice to hear, we did not touch anything today. You could also enable the chrome task manager (top-right the three dots > More Tools > task manager) to see how much memory the tab is using. Would be helpful to know. I tested it on linux and macos, both were between 310mb and 340mb with spikes to 450 here and there.

**Comment by JohnCoene** [comment]
This happens after the load of the data, when @AxelBigOmics showed me it was very quick to occur: after load Chrome seems to hang then presents the "Aw snap!" popup.

**Comment by AxelBigOmics** [comment]
Just to update, I experienced the problem again this morning while using v2.8.5 on chrome. I uploaded a fresh dataset, tasked the platform with computing it and when I looked back after about 1h and the "Aw Snap" message had appeared. I did not even access any of the tabs, just had the platform turn the CSV files into a PGX file. It did that, so the crash happened afterwards

**Comment by stefanreifenberg** [comment]
Good to know. So its not the app crashing after leaving it running for some time. The problem is related to the data preprocessing. Our plan is to move the whole preprocessing step to a separate service which is running on the server. That should eliminate the memory error.

**Comment by JohnCoene** [comment]
Hopefully, to clarify the preprocessing runs fine, it's the browser that "crashes" and gives [this](https://support.google.com/chrome/answer/95669?hl=en&co=GENIE.Platform%3DAndroid)

**Comment by AxelBigOmics** [comment]
As a further update, I do not encounter the problem with version 2.8.0 of the platform. It appears to be specific to 2.8.5 (or maybe a version in-between). With Ivo's help, I got some error messages that appeared when loading a new dataset into the platform, which I'm attaching below.  I will add more later when the platform crashes.

![Sc1](https://user-images.githubusercontent.com/85561624/157229623-82dd8b71-db10-406b-9c66-91ccec6ecc6c.png)
![Sc2](https://user-images.githubusercontent.com/85561624/157231569-718259e4-baf9-4101-b4d0-e653ad4e818f.png)

**Comment by JohnCoene** [comment]
These errors point to shiny itself, nothing on our side, as far as I can tell. 

Maybe we can make sure we use the latest stable version of shiny?

**Comment by AxelBigOmics** [comment]
Yes, that's one thing we could/should try. I could make an updated docker.
The Docker is a little behind with the versions of R and Shiny. I was
waiting for Ubuntu 22.04 which should be LTS.

**Comment by ivokwee** [comment]
> Maybe we can make sure we use the latest stable version of shiny?

So from my last poll, everyone is using Shiny 1.7.1. The R versions that everyone is using (and platform) are different: 4.0.1, 4.0.4, 4.1.2, 4.1.3.

**Comment by JohnCoene** [comment]
renv will eventually fix that.

New theme uses bs5 which requires > 1.7.0

**Comment by JohnCoene** [comment]
Also on this, I think renv could also speed up docker build (copy dependencies instead of reinstall from docker), not sure it's a great idea @marcosci
