### ISSUE TITLE
"Email sent" message after logging in with email on deployed app takes too long

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#516]
When you log in with email on the deployed application, it takes sometimes 5 - 10+ seconds to get the "email sent" confirmation. This should be instantaneous or at least <1 second given that firebase auth is async. I believe this is fixed in the repo, but we need to confirm that this change is also carried through on the deployed app.

However, if the issue is still present then maybe we should check that some server code isn't getting inadvertently run... maybe when the user enters their email, the `auth` reactive value gets triggered and makes some server code run.

**Comment by ivokwee** [comment]
There was previously your waiter spinner. Not sure what happened but it's gone now. That was at least good to let the user wait. Hope I didn't do it with my last refactor in AuthenticationModule. Can you please check?

**Comment by ivokwee** [comment]
Yes. I do not see such a delay in the shinyproxy deployments. it seems just the docker swarm deployments. Perhaps it needs some config changes. I let Xavier look at it

**Comment by ivokwee** [comment]
Please also check some comments on issue #528
