### ISSUE TITLE
document if "continuous" variable names like `age` and `height` are accepted in OPG

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#518]
document if "continuous" variable names like `age` and `height` are accepted in OPG

**Comment by mauromiguelm** [comment]
I tested age and height, three continuous variables as in the table below


**upload module:**

<img width="583" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/0c5554da-3d29-45cb-afb5-085ba6cf94d2">

**sample information dataview:**

<img width="761" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/e36a2ac3-eba6-4731-af24-a05459bfaf28">


**results:**

Continuous variables get kicked out from the phenotype selection.. is this correct @ivokwee, should we somehow force dichotomize it? Based on the feedback I will update documentation and do the changes.

<img width="287" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/0319ef38-1c06-4a66-a2f5-fb1367d36114">

<img width="761" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/3c102de0-f9ff-4ce1-b089-c1e0c70bd0ee">

<img width="374" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/6baa531f-4a95-4720-90a4-9ad4db6d15e7">

**Comment by ivokwee** [comment]
In the pgx object there used to be, or still is, pgx$samples and pgx$Y. The latter should be a cleaner and discretized version of the former. I try to keep pgx$samples as original as possible. But I failed to use this consistently. The nicest thing would be in the UI to check and ask to discretize continuous variables: 2-3-4 groups. Ideally we should be able to handle statistics for CV. But now you have to discretize or use them solely for visualization. Would be nice also to be able to plot CV against other vars (some people asked that).

**Comment by ivokwee** [comment]
Yes. There is code somewhere that tries to intelligently detect CV or Discrete var. Not always robust. But such a code is very important for creating auto contrasts.

**Comment by mauromiguelm** [comment]
Follow up:

1. The phenotype association plot uses pgx$samples, which still has the continuous values.
annot <- pgx$samples
<img width="284" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/11e7e94c-66df-40dd-ab59-22da105d2b00">

2. pgx$Y on the other hand, is lacking the discretized values. 
<img width="267" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/459dce11-8e9b-4a7b-99b9-e61e43207dc0">

It seems pgx$Y, for some reason (bug?) is not discretizing continuous variables anymore.

Two solution that comes to mind here:
1. Do it at the pgx check level, where we discretive ourselves and tell the user we will discretize these values. This is very easy to do in crosscheckInput function. We could even create new columns age > age_discrete in pgx$samples, but that would not keep pgx$samples clean anymore.
2. Find the bug on why pgx$Y is not being discretized, or add that functionality. But since pg$Y is created inside pgx.compute (or initialize), its way more difficult to inform the user continues variables will be discretized, compared to doing it in the check functions, where we already have all systems in place to tell user and make changes to inputs.

I am not sure which of the options I should go for, but it seems important that if age, height or any random_continuous variables are removed from the phenotypes, we should somehow tell the user or fix it,

Cheers,
M

**Comment by mauromiguelm** [comment]
@ivokwee @ncullen93 this is what we discussed today, how should we proceed?

**Comment by mauromiguelm** [comment]
> It seems pgx$Y, for some reason (bug?) is not discretizing continuous variables anymore.

we first need to understand why pgx$Y is not showing continuous values, any idea how much work updating pgx$samples to pgx$Y will require?

**Comment by ivokwee** [comment]
Still relevant. Known improvemtn. But closing as stale.
