### ISSUE TITLE
Simplify contrasts input

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#527]
**Problenm with current contrasts:**

- we have double information in current "short contrast form", japan is mentioned twice, which is unnecessary
- group column is unnecessary, we can "remove" that need simply by using the real samples colunm as contrast column (!!!)
- if we reshuffle things slightly, we can get to a much more robust short contrast form..
- require additional data prep steps in samples file, which adds frustation to the user

More details about contrasts, short and long forms: https://omicsplayground.readthedocs.io/en/latest/dataprep/contrasts.html

**Old version:**

<img src="https://github.com/bigomics/omicsplayground/assets/28757711/09d44b74-6165-4795-a947-a624ec8e151e" width=70% height=70%>

**New version:**

<img src="https://github.com/bigomics/omicsplayground/assets/28757711/580ebd3c-8331-484e-bfc9-4e0a51b6db97" width=30% height=30%>

- allows for multiple compairsons
- removes need for group column
- is easier to understand, as it requires less steps and have direct match to sample columns
- we can even thing about building nested comparisons, I have a few ideas but the easiest would be separate the column names by /. For example `country / age` and `japan / young` would create nested comparisons
- would be easier to create programatically (DNAnexus)...
- `1/-1` could be replaced by numerator/denominator, or a simpler term. I still could not find it.

**Comment by ivokwee** [comment]
I would not change it if not needed. It might break all previous pgx files. I think manual contrast making should just be avoided. We already can do nested comparison by taking the "product" of two phenotype, that is creating japan_old vs japan_young, and switzerland_old vs switzerland_young. Then you can also create japan_old vs switzerland_old, etc. I think we use the 'dot' in the UI to do that.

**Comment by mauromiguelm** [comment]
Hi Ivo,

1. @products of phenotypes! IThe recommended action for nested comparisons (via files) is to combine two or more columns in the samples file? I will add to documentation, as I did not see any reference to this possibility in our documentation!

2. regarding encouraging or even allowing people to make the contrasts file or not, do we have any statistics on how many people use the contrasts.csv (3 files) versus contrast creation on the platform?

3. this should not influence old pgx files, as contrast creation should happen before computing the pgx. The direction I would like to go is that the outcome of new or old contrasts creation should be the same, just the contrast.csv file input would change (for a simpler format). And we could even allow both formats (with group column as well).

M

**Comment by ivokwee** [comment]
I think we already have too many formats allowed. It's becoming too many choices, therefore confusing.

**Comment by ivokwee** [comment]
Let's close this. I think we shouldn't make another contrast format. It is better to make the contrast UI better. We don't expect (or want) people to use the CLI.
