### ISSUE TITLE
`Email sent` message dissapears shortly after clicking "Send link"

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#528]
1. The message "email sent" takes too long to appears, and no spinner is shown
2. The message "email sent" dissapears, it should remain until the email is opened.

The combination of the two gives the feeling that we have to keep clicking on "Send link".

<img width="229" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/d22403c5-c8ef-4ccc-8b07-b5f402087755">

**Comment by ivokwee** [comment]
I just noticed that on the shinyproxy deployments it is fast like locally. It is on playground.bigomics.ch (Docker swarm) that it is slow.

**Comment by ivokwee** [comment]
This is partially duplicated in #516 . Closing this one. Please open new issue if you think you want the message to stay longer visible.
