### ISSUE TITLE
Cell Type profile plot colours are confusing in V3

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#530]
Hi,

I'm testing the docker version of the platform (v3.0-RC17.230627) and I am rather confused by how the samples are coloured in the Cell Type profiling tab. As you can see from the example below, I am dealing with skin cells, which are correctly identified as the first match. However, the samples are coloured in dark grey, which I interpret as bearing no correlation, whereas other (incorrect) tissue types are coloured in red. I find this very confusing and so, I expect, will other users. Can you explain and eventually alter the colour scheme?

![image](https://github.com/bigomics/omicsplayground/assets/85561624/012c05fa-98d3-41d3-bb08-b025374b42b0)

**Comment by mauromiguelm** [comment]
To the best of my knowledge, we cannot change the points colors. That means we should show the color legend for what is being plotted.. agree with Axel that colors are not clear!

Not sure where we should show legends in this case, probably one legend for all plots on the right.

This is a nice problem for @ShaliniPandurangan

**Comment by ShaliniPandurangan** [comment]
The zlim were scaling with respect to the data in the each subplot, other than respecting a common zlim.

Setting the zlim manually to the min and max value of the dataframe fixed the issue.
