### ISSUE TITLE
Switching to a newly uploaded datasets results in a crash in V3

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#532]
Hi,

I am using v3.0-RC17.230627 and I noticed that every time I upload a new dataset and start working with a different one in the meantime, by the time the dataset is ready and the platform asks me if I want to switch, the platform crashes with the following error message if I click yes (this has happened with any dataset I uploaded):

> Error Message
> attempt to set an attribute on NULL
> 
> Error traceback
> 93: h
> 92: .handleSimpleError
> 91:
> 90: ..stacktraceon..
> 89: .func
> 88: withVisible
> 87: withCallingHandlers
> 86: contextFunc
> 85: env$runWith
> 84: force
> 83: domain$wrapSync
> 82: promises::with_promise_domain
> 81: withReactiveDomain
> 80: domain$wrapSync
> 79: promises::with_promise_domain
> 78: ctx$run
> 77: self$.updateValue
> 76: ..stacktraceoff..
> 75: getCurrentContrast
> 74:
> 73: ..stacktraceon..
> 72: .func
> 71: withVisible
> 70: withCallingHandlers
> 69: contextFunc
> 68: env$runWith
> 67: force
> 66: domain$wrapSync
> 65: promises::with_promise_domain
> 64: withReactiveDomain
> 63: domain$wrapSync
> 62: promises::with_promise_domain
> 61: ctx$run
> 60: self$.updateValue
> 59: ..stacktraceoff..
> 58: getTopProfiles
> 57: eval_tidy
> 56: eventFunc
> 55: force
> 54: withVisible
> 53: withCallingHandlers
> 52: domain$wrapSync
> 51: promises::with_promise_domain
> 50: captureStackTraces
> 49: doTryCatch
> 48: tryCatchOne
> 47: tryCatchList
> 46: tryCatch
> 45: do
> 44: hybrid_chain
> 43: observeEvent(getTopProfiles())
> 42: contextFunc
> 41: env$runWith
> 40: force
> 39: domain$wrapSync
> 38: promises::with_promise_domain
> 37: withReactiveDomain
> 36: domain$wrapSync
> 35: promises::with_promise_domain
> 34: ctx$run
> 33: run
> 32: withCallingHandlers
> 31: domain$wrapSync
> 30: promises::with_promise_domain
> 29: captureStackTraces
> 28: withCallingHandlers
> 27: shinyCallingHandlers
> 26: force
> 25: withVisible
> 24: withCallingHandlers
> 23: domain$wrapSync
> 22: promises::with_promise_domain
> 21: captureStackTraces
> 20: doTryCatch
> 19: tryCatchOne
> 18: tryCatchList
> 17: tryCatch
> 16: do
> 15: hybrid_chain
> 14: flushCallback
> 13: FUN
> 12: lapply
> 11: ctx$executeFlushCallbacks
> 10: .getReactiveEnvironment()$flush
> 9: flushReact
> 8: serviceApp
> 7: ..stacktracefloor..
> 6: withCallingHandlers
> 5: domain$wrapSync
> 4: promises::with_promise_domain
> 3: captureStackTraces
> 2: ..stacktraceoff..
> 1: shiny::runApp

**Comment by ivokwee** [comment]
Please update to RC18 and check.

**Comment by ESCRI11** [comment]
Latest master branch does not crash under those conditions.
