### ISSUE TITLE
Signing in to app via email opens a second tab and doesn't close the first tab

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#535]
When I sign into the deployed app by following the email link, the link opens the application in a second tab and leaves the original tab where I signed in open. Not sure if there is a way to automatically close the first tab when the user has signed in to the second tab, or if there is a way to make the email link go to the first tab that I'm missing.

**Comment by mauromiguelm** [comment]
this happens to me since the new login was implemented.. totally valid!

**Comment by ivokwee** [comment]
We can close the first tab after sending the email perhaps with JS. The other ideas was to make a separate login shiny app that is small and lightweight so it doesnt need to load the whole application. The ultimate idea is to have the login integrated into our wordpress website with some firebase login.

**Comment by ESCRI11** [comment]
New login method makes this issue outdated
