### ISSUE TITLE
Potentially move data loading settings to the table itself instead of the sidebar

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#536]
It's a bit unclear on first glance what the settings do on the data loading tab (see figure below). A bit of experimentation shows that these filter the data loading table. Should these settings be moved to an options dropdown menu on the data loading table itself? This would be a bit more intuitive and would allow us to get rid of the settings bar on this page (similar to the data upload page), thereby giving much more space to the user to see the table and the figure. 

Happy to hear thoughts on this.

<img width="176" alt="Screen Shot 2023-06-29 at 12 08 43 PM" src="https://github.com/bigomics/omicsplayground/assets/13004360/65589ad5-010b-4152-a62c-723ba59e03b6">

**Comment by ESCRI11** [comment]
Makes sense to me. +1 from my side
