### ISSUE TITLE
Boostrap tab alert harmonization

### ISSUE THREAD

**Issue by ESCRI11** [bigomics/omicsplayground#540]
The boostrap alert boxes placed on the application tabs are not consistent. On sone tabs they are properly spaced (Figure 1), while on others are glued to the content (Figure 2).

Also, when dismissing them, there is a leftover gap on the ones properly spaced (Figure 3/4). This is also seen on load dataset tab, where there is a really big leftover gap.

Go over each board containing a `bs_alert` element and fix both issues to provide a consistent experience.

Make sure that everything is also consistent when user settings is `enable_info = FALSE`.

Figure 1:
<img width="152" alt="image" src="https://github.com/bigomics/omicsplayground/assets/10220503/61f26d74-3df6-428e-951c-1b0688fa3506">

Figure 2:
<img width="179" alt="image" src="https://github.com/bigomics/omicsplayground/assets/10220503/cf012daa-7814-426e-aa5b-2bf4e0f68217">

Figure 3:
<img width="733" alt="image" src="https://github.com/bigomics/omicsplayground/assets/10220503/d9fb2418-d80a-4e7a-b38d-779815f3e8f4">

Figure 4:
<img width="747" alt="image" src="https://github.com/bigomics/omicsplayground/assets/10220503/2ae626fa-08f0-480d-a066-ec0f031cc36b">

**Comment by ESCRI11** [comment]
Working on it at the moment

**Comment by phisanti** [comment]
@ESCRI11, did you managed to fix this?

**Comment by ESCRI11** [comment]
Still work in progress, found exactly what was causing it, just need to fix
