### ISSUE TITLE
Adding "exclude" option or multiple selection for genesets annotation

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#548]
This is more a request than a bug, but I noticed that by expanding the pathways and genesets database, a lot of the informative pathway get "drowned" by non-descriptive gene silencing or upregulation experiments. This is particularly noticeable when I select "all" under the "Geneset UMAP".

While it is great to have more datasets for comparative analysis, I would appreciate the option of excluding some of them (e.g. LNCHUB, RNASEQ, BIOPLEX), while leaving the rest. This is because the more thoroughly descriptive HALLMARK/Msig/etc... pathways are more informative when initially exploring the data. 

In fact, retaining the dataset collections that were present in V2 without the new ones ( like a new "all minus"option) would be great. Would it be possible to add such an option in the scroll down menu?

![image](https://github.com/bigomics/omicsplayground/assets/85561624/c760f749-daae-4b8d-866a-1dfab113d645)

**Comment by ivokwee** [comment]
Initally I thought this is confusing "all minus"?? minus what? I think Axel means a "exclude" function. We could either allow multiple selection (which I prefer more), perhaps even in the global settings page.
