### ISSUE TITLE
[R] Cleanup global environment 

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#57]
Currently everything is accessible from everywhere and it's impossible to know where a variable comes from and who should use it.

- A quick easy “solution” to add some organization and clarity is to simply not create many global variables from many different files. Variables created within the same file should be grouped together and should be more explicit about where they come from. For example, in global.R, instead of creating variables [OPG, RDIR, WATERMARK] and more, you can create a single .globals <- new.env() and the assign the same variables into .globals. This way it's more clear where a variable came from, they're grouped together, and you limit the number of objects in the global scope.
- A better solution, but it would also require more work, is to use a more modular framework (not to be confused with shiny's module feature). It would allow you to explicitly import and export certain objects from each source file, which will improve long term maintainability. There are two options for this: the {modules} package and the {box} package. I personally recommend {box} since it's a much more widely used package and its author is a well established member of the R community with many great contributions over the years.

**Comment by ivokwee** [comment]
This is a related comment from Appsilon:

"Long time no see. I wanted to share one update - we have recently switched our projects from using wahani/modules to using box - https://github.com/klmr/box  The usage is quite similar, however, at the same time the overhead of memory usage is lower and it is much leaner to use."

**Comment by ivokwee** [comment]
Reopened.Should find a better solution of our globals. Many are loaded in the initial lib/sysdata.rda object.

**Comment by ivokwee** [comment]
closing. playdata is used for global data objects. Let's try to minimize the globals in app.
