### ISSUE TITLE
refactor upload/load boards: replace `getPGXDIR()` by `auth$options$user_dir`

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#573]
yep we need to replace getPGXDIR by auth$options$user_dir, but since its so common in the loading board, I decided to do the trick within the reactive.

this will require a large amount of refactoring, as we need to enter each .R file and change fn arguments, remove parentethesis from getPGXDIR(), as its not a reactive anymore, etc.. 

maybe a new issue for a future to-do

<img width="836" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/36b6784c-2afe-4018-bac2-1aee3868f61b">

_Originally posted by @mauromiguelm in https://github.com/bigomics/omicsplayground/pull/571#discussion_r1261194607_

**Comment by phisanti** [comment]
Do you think that running:
```r
my_r_file <- readLines("path/to/script.R")
my_r_file<- gsub("getPGXDIR\\(\\)|getPGXDIR", "auth$options$user_dir", my_r_file)
writeLines(my_r_file, "path/to/script.R")

```
across R files would do the job? If should be possible to add exceptions to avoid cases such as `getPGXDIR = getPGXDIR` or similar if needed.

**Comment by ivokwee** [comment]
as nicke said better do it manually. or  but otherwise   

for i in \`grep -rl  getPGXDIR components\`; do sed -i "s/getPGXDIR\\(\\)|getPGXDIR|/auth\$options\$user_dir/g" $i; done

or something like that...

**Comment by ivokwee** [comment]
or

`grep -lr getPGXDIR components | xargs -0 sed -i  "s/getPGXDIR/auth\$options\$user_dir"
`

not sure if I have to do \\$ or \\\\$  ...

**Comment by phisanti** [comment]
Whichever method is used, I think only few instances remain:
    file                                                                              line line_number
1. ./omicsplayground/components//app/R/server.R         ConnectivityBoard("cmap", pgx = PGX, getPgxDir = reactive(auth$user_dir))         365
2. ./omicsplayground/components//board.connectivity/dev/app_server.R                                                     getPgxDir <- reactive("data")          10
3. ./omicsplayground/components//board.connectivity/dev/app_server.R                               server <- ConnectivityBoard("cmap", pgx, getPgxDir)          11
4. ./omicsplayground/components//board.connectivity/R/connectivity_server.R                               ConnectivityBoard <- function(id, pgx, getPgxDir) {           7
5. ./omicsplayground/components//board.connectivity/R/connectivity_server.R                                              db2 <- file.path(getPgxDir(), sigdb)          95
6. ./omicsplayground/components//board.connectivity/R/connectivity_server.R                                              db2 <- file.path(getPgxDir(), sigdb)         110
7. ./omicsplayground/components//board.connectivity/R/connectivity_server.R                                                               return(getPgxDir())         115
8. ./omicsplayground/components//board.connectivity/R/connectivity_server.R                                                             pgxdir <- getPgxDir()         195

**Comment by ivokwee** [comment]
ok. @phisanti  can you please continue. or do you need help?

**Comment by phisanti** [comment]
@ivokwee, I can hit those tomorrow or on Sat.

**Comment by phisanti** [comment]
While working on changing the variables name, I tried to run the Connectivity board and got the following error:

```r
Timing stopped at: 52.89 11.77 215.8
Warning: Error in serialize: error writing to connection
  180: h
  179: .handleSimpleError
  178: serialize
  177: sendData.SOCKnode
  176: parallel:::sendData
  175: .send_to
  174: .send_to
  173: .send_all
  172: .send_all
  171: .manager_cleanup
  170: .manager_cleanup
  169: .bploop_impl
  168: bploop.lapply
  167: bploop
  166: .bpinit
  165: bplapply
  164: bplapply
  163: fgseaSimpleImpl
  162: fgsea::fgseaSimple
  161: system.time
  160: pgx.correlateSignatureH5
  159: playbase::pgx.computeConnectivityScores
  158: eval [board.connectivity/R/connectivity_server.R#218]
  157: eval
  156: shiny::withProgress
  155: <reactive> [board.connectivity/R/connectivity_server.R#217]
  154: ..stacktraceon..
  153: .func
  152: withVisible
  151: withCallingHandlers
  150: contextFunc
  149: env$runWith
  148: force
  147: domain$wrapSync
  146: promises::with_promise_domain
  145: withReactiveDomain
  144: domain$wrapSync
  143: promises::with_promise_domain
  142: ctx$run
  141: self$.updateValue
  140: ..stacktraceoff..
  139: compute_connectivity
  138: <reactive> [board.connectivity/R/connectivity_server.R#232]
  137: ..stacktraceon..
  136: .func
  135: withVisible
  134: withCallingHandlers
  133: contextFunc
  132: env$runWith
  131: force
  130: domain$wrapSync
  129: promises::with_promise_domain
  128: withReactiveDomain
  127: domain$wrapSync
  126: promises::with_promise_domain
  125: ctx$run
  124: self$.updateValue
  123: ..stacktraceoff..
  122: getConnectivityScores
  121: <reactive> [board.connectivity/R/connectivity_table_similarity_scores.R#33]
  120: ..stacktraceon..
  119: .func
  118: withVisible
  117: withCallingHandlers
  116: contextFunc
  115: env$runWith
  114: force
  113: domain$wrapSync
  112: promises::with_promise_domain
  111: withReactiveDomain
  110: domain$wrapSync
  109: promises::with_promise_domain
  108: ctx$run
  107: self$.updateValue
  106: ..stacktraceoff..
  105: func
  104: exprFunc [ui/ui-TableModule2.R#190]
  103: widgetFunc
  102: ::
htmlwidgets
shinyRenderWidget
  101: func
  100: force
   99: withVisible
   98: withCallingHandlers
   97: domain$wrapSync
   96: promises::with_promise_domain
   95: captureStackTraces
   94: doTryCatch
   93: tryCatchOne
   92: tryCatchList
   91: tryCatch
   90: do
   89: hybrid_chain
   88: renderFunc
   87: renderFunc
   86: force
   85: domain$wrapSync
   84: promises::with_promise_domain
   83: renderFunc
   82: output$cmap-connectivityScoreTable-datasets-datatable
   81: ..stacktraceon..
   80: orig
   79: func
   78: withCallingHandlers
   77: domain$wrapSync
   76: promises::with_promise_domain
   75: captureStackTraces
   74: withCallingHandlers
   73: shinyCallingHandlers
   72: force
   71: domain$wrapSync
   70: promises::with_promise_domain
   69: private$withCurrentOutput
   68: force
   67: withVisible
   66: withCallingHandlers
   65: domain$wrapSync
   64: promises::with_promise_domain
   63: captureStackTraces
   62: doTryCatch
   61: tryCatchOne
   60: tryCatchList
   59: tryCatch
   58: do
   57: hybrid_chain
   56: force
   55: withVisible
   54: withCallingHandlers
   53: domain$wrapSync
   52: promises::with_promise_domain
   51: captureStackTraces
   50: doTryCatch
   49: tryCatchOne
   48: tryCatchList
   47: tryCatch
   46: do
   45: hybrid_chain
   44: observe
   43: <observer:output$cmap-connectivityScoreTable-datasets-datatable>
   42: contextFunc
   41: env$runWith
   40: force
   39: domain$wrapSync
   38: promises::with_promise_domain
   37: withReactiveDomain
   36: domain$wrapSync
   35: promises::with_promise_domain
   34: ctx$run
   33: run
   32: withCallingHandlers
   31: domain$wrapSync
   30: promises::with_promise_domain
   29: captureStackTraces
   28: withCallingHandlers
   27: shinyCallingHandlers
   26: force
   25: withVisible
   24: withCallingHandlers
   23: domain$wrapSync
   22: promises::with_promise_domain
   21: captureStackTraces
   20: doTryCatch
   19: tryCatchOne
   18: tryCatchList
   17: tryCatch
   16: do
   15: hybrid_chain
   14: flushCallback
   13: FUN
   12: lapply
   11: ctx$executeFlushCallbacks
   10: .getReactiveEnvironment()$flush
    9: flushReact
    8: serviceApp
    7: ..stacktracefloor..
    6: withCallingHandlers
    5: domain$wrapSync
    4: promises::with_promise_domain
    3: captureStackTraces
    2: ..stacktraceoff..
    1: shiny::runApp
```

While the screen gets fronze at:
![image](https://github.com/bigomics/omicsplayground/assets/33370667/d0d45093-b0ef-40b7-a57a-6e73cc3433ea)
It happens in both, the branch that I created and the main branch. Does anyone has the same problem? @ncullen93 @ivokwee?

**Comment by ivokwee** [comment]
PR was recently merged for this. I don't see the problem from my part. Closing this issue. Reopen if needed.
