### ISSUE TITLE
Refactor Orca server 

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#59]
A significant portion of the startup time is taken up by creating the Orca server (~half a minute for me). It seems the only use of it is to download static plotly plots. I would be worthwhile looking into an alternative such as plotly::orca and removing the initOrca function.
There is some issue between shiny and orca on Windows (at least for me) where it doesn't like the temporary file path, but can be resolved by making a temporary file within the project and copying that file to the file argument in downloadHandler.

**Comment by ivokwee** [comment]
No need. We now use Kaleido. Orca is deprecated.
