### ISSUE TITLE
Awe snap error out of memory error in chrome browser

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#591]
A user is reporting an "Awe snap, out of memory error"in chrome browser in V3. See email and image below. Does not happen in V2. Posting this because recently some of you also got this. 

> Hi Ivo,
> Yes it can be a browser problem, I will try on Firefox or clear Chrome's browser cache. I am using windows and Chrome yes.
> Regarding the details, the crash happens everytime I try to load the dataset in, it starts to say that the data is being loaded and then that message I showed you pops up and I have to refresh the page.
> Important note is that it only happens in this version 3, if I use version 2 I can load my datasets normally and work without a problem.
> Also like I mentioned before it only happens in my PC.
> I was in the load dataset page. I tried to load the Bousioutis_TAMs dataset which I myself uploaded in the past. But it happens when I try to load any dataset.
> It takes about 10sec from the moment I try to load the data until the error occurs.
> I hope this helps.
> Best,Pedro

![image](https://github.com/bigomics/omicsplayground/assets/19613146/dc401229-cdca-4e4e-9e31-5d6365aad7f1)

**Comment by ivokwee** [comment]
Another report from different user (claudia t. uantwerpen):

> 1. What dataset did you use?  Is it OK that we test your dataset? à RNAseq dataset called ‘mitochondrial_methylation_cell_lines’, Ok to test dataset
> 
> 2. What browser did you use? Which OS? à Used chrome with Windows 10
> Editie    Windows 10 Home
> Versie   22H2
> Installatiedatum              ‎16/‎11/‎2020
> Build van besturingssysteem     19045.3208
> Ervaring               Windows Feature Experience Pack 1000.19041.1000.0
> 
> 3. What are the specifications of the computer you used? à Asus VivoBook S15
> 
> Apparaatnaam DESKTOP-3S2LH1K
> Processor           Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
> Geïnstalleerd RAM-geheugen   8,00 GB (7,88 GB beschikbaar)
> Apparaat-id       64F1CB3F-8ED9-464A-A23B-D1A45DE6B84A
> Product-id          00325-96374-63978-AAOEM
> Type systeem   64-bits besturingssysteem, x64-processor
> 


![image](https://github.com/bigomics/omicsplayground/assets/19613146/5858edc2-b7aa-40ba-958a-efd8bbc6b0d1)

**Comment by ESCRI11** [comment]
@ivokwee This is actually caused by these lines of codes (I can reproduce locally). https://github.com/bigomics/omicsplayground/blob/master/components/ui/ui-DropDownMenu.R#L90-L93

Removing them fixes the issue although it brings back issue #492

**Comment by ivokwee** [comment]
oh. good find! but that is bad news becuase the clipping is really annoying. I guess we have so many plots that the browser gets overloaded? We cannot use the singleton() here because it uses id?  

What shall we do? revert back and ask Carson again?

**Comment by ESCRI11** [comment]
I would revert back for now and investigate. This bug is a total no-go, the other one is just annoying.

**Comment by ivokwee** [comment]
I reverted manually. His second fix was almost good, some little window resize sometimes, but it affected also the drop-down in the welcome page top right becoming unresponsive. So he went for id selector instead which probably overloads the browser

**Comment by ivokwee** [comment]
Possible solution in PR #606

**Comment by phisanti** [comment]
@ESCRI11 @ivokwee I tested the latest version of dev-card-clipping (commint 71eee543f632b0eebeb32c19d5c38b84e72d97a3) and it works fine. No out-of-memory error.
