### ISSUE TITLE
Move GSETS object into database (SQLite)

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#60]
Reading this huge list takes several seconds, is it absolutely necessary? Maybe consider moving this data into eg. a SQLite database where you can reference the required IDs rather than loading the entire list on init.

**Comment by ivokwee** [comment]
Solved for the moment. Instead of the huge list, we now store a sparse matrix and rebuilt the list on the fly (see pgx-init.R). Saving the sparse matrix is way more efficient in saving and loading.
