### ISSUE TITLE
Support for bacterial strains

### ISSUE THREAD

**Issue by mmatster** [bigomics/omicsplayground#600]
Dear authors of the omicsplayground, I would like to use the tool in my research but I work with omic data derived from bacterial strains or communities. So, I would like to ask you if it is possible to add support for the following seven bacterial strains: Streptococcus thermophilus JIM8232, Lactococcus lactis subsp. lactis IL1403, Lactiplantibacillus plantarum JDM1, Lacticaseibacillus paracasei 8700:2, Pediococcus pentosaceus ATCC 25745, Lactobacillus delbrueckii subsp. bulgaricus 2038, and Latilactobacillus sakei subsp. sakei 23K. The list of the gene IDs of the expression matrix is from the ENSEMBL for Bacteria. Thank you.

**Comment by ivokwee** [comment]
Hi Mmaster.  Please repost your feature request to our User forum on our community forum at Google groups. https://groups.google.com/g/omicsplayground

We keep this Github issue for software related bugs and questions. Your request is noted but please continue any discussion in the google group.
