### ISSUE TITLE
Keyword option under "word cloud"->"Enrichment plots" is inactive (v3.2.11-master230722)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#602]
The "Enrichment plots" keyword option under "word cloud" (v3.2.11-master230722) appears to serve no function. Changing the term in the box has no effect. If that's intended, it might be better to remove it.

![image](https://github.com/bigomics/omicsplayground/assets/85561624/1878ff27-38e3-4844-954e-36e07965cfad)

**Comment by ESCRI11** [comment]
@ivokwee Can you confirm if that keyword functionality should be implemented somehow (I would guess overwritting this if input is provided https://github.com/bigomics/omicsplayground/blob/master/components/board.wordcloud/R/wordcloud_plot_enrichment.R#L53). If not, I will just remove it from the options

**Comment by ShaliniPandurangan** [comment]
@ESCRI11 , @ivokwee suggested to remove the keyword functionality.
