### ISSUE TITLE
In case pgx fail to compute, warn user via email

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#603]
we should write a small script to send a warning email that the pgx fail, similar to the warning below

<img width="508" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/62864da3-c9b7-4890-84b8-174a0287ea5e">

**Comment by mauromiguelm** [comment]
this came from Ivo, and we already discussed several times that this is a good approach, so I guess we can move forward ;)

**Comment by phisanti** [comment]
This looks a very interesting project. If no one is working on it, I got a couple of ideas. It could be as simple as:
```r
  tryCatch({
    foo(x)
  }, error = function(e) {
    send_email(e$message)
  })
  
  ```
  Please, let me know @ivokwee @mauromiguelm

**Comment by mauromiguelm** [comment]
I am actually working on it since Monday, sorry I did not assign it myself!

**Comment by mauromiguelm** [comment]
I can send the solution for you to review, but tryCatch will not work as we are running computation in an external process

**Comment by phisanti** [comment]
Sounds good. Let me know if you need any help!
