### ISSUE TITLE
Missing databases under "Functional annotation of clusters" in v3.2.15-master230727

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#605]
Hi,

I noticed that when I want to select the database from the "Reference set" scroll down menu  to use for the functional annotation of clusters in the "Cluster Samples" module, several databases are not present (e.g. GO, see figure below). Since GO is widely use, I do not think this was intentional, so reporting it as a bug to be fixed.

![image](https://github.com/bigomics/omicsplayground/assets/85561624/7cfa966f-865f-45f0-893c-bc63c8c5b638)

**Comment by AxelBigOmics** [comment]
The list of databases for functional annotation is still incomplete as of v3.2.23-master230823. Is it intended to remain incomplete (e.g. no GO terms for functional annotation)? If so, why have _T-cell related_ (of limited application) and not GO terms?

**Comment by mauromiguelm** [comment]
Hi Axel, GO will only appear if at least 3 genesets will show up and when the reference geneset will be updated in #689 This can be closed due to a more specific issue. 

This can be seen on line ```ann.types <- ann.types[cc >= 3]```
