### ISSUE TITLE
Add option (default) to have an independent scaling of y-axis on volcano grids

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#613]
**Summary:** 

1. Add option (default) to have an independent scaling of y-axis, and not a single scaling across all volcano grids, as sometimes there are big differences between statistics which makes impossible to see results.

2. In v2, we had independent scaling for each plot. We should have both options, the user should choose.

3. these types of plots (volcano grids) are present on diffexpr and genesets, so be sure not to miss any.

<img width="761" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/22eee2cd-c067-4326-bee7-7e22dc0f02bf">

**Comment by phisanti** [comment]
This should be an easyone. I will try to get it done today.
