### ISSUE TITLE
improve pgx computation spinner

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#620]
**problem:** a few users complained that the spinner is not visible enough and they do not notice that the computation is running.

**solutions:** Maybe we can add a log widget on the top bar (similar to chirp), where the main activities of the user are tracked and every time a pgx is uploaded we have a "new" message . Or simply make the widget more noticeable.

<img width="401" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/17515c36-1fd9-44c8-b7d3-d29cee595f83">

**Comment by mauromiguelm** [comment]
and sometimes spinner dissapears or not appears, this has to be fixed as well!

**Comment by ivokwee** [comment]
To me the spinner is big enough but perhaps the meaning of the spinnng circle was not grasped as computing in the background. The disappearing spinner or not appearing is a realistic problem.

**Comment by mauromiguelm** [comment]
regarding dissapearing spinner, I originally attached the spinner to the header. That was a bad idea, as the header gets refreshed (this should not happen).

We should open a new issue as to why the header refreshes.

An easy solution is to attach the html snippet to the end of html file, something like `document.body.insertAdjacentHTML('beforeend', snippet);` should work
