### ISSUE TITLE
Checkbox for selecting specific datasets, and highlight filter in tSNE/UMAP

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#622]
User suggested adding a checkbox option to the dataset table to group/filter and compare datasets based on specific disease/study such as clinical samples or plasma proteomics.

Ideally, those highlighted dataset will be colored in the tSNE plot.

**Comment by ivokwee** [comment]
In which module? is it the main dataset table in the loading panel? The tSNE is now dynamic and reacts on the filtered table. I think Daniel suggested this and confirmed it should be enough to just filter the table. Closing this issue.

**Comment by mauromiguelm** [comment]
Load > load dataset > My Library.

No, only half of what Daniel suggested was implemented. He wants to highlight one or multiple projects by clicking on the table, that is not implemented, see https://docs.google.com/spreadsheets/d/1ybTkHo1zDTPe-dT-nF5To0inR8xbRwFlRm751pWa5Ww/edit#gid=545946193&range=53:53. It starts on minute 1.50, so you really need to watch the full video.
