### ISSUE TITLE
Add statistics to clustering annotation in clustering modules

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#623]
**Goal**: Find a way to filter/identify statistically significant clusters across boards that use these clusters (especially cluster board)

**Problem**: For the cluster annotations in the clustering modules: There are no statistics included in the RNA-seq analyses to help the reader understand which pathways are significant. (so no statistics for the correlation values).

**Comment by ivokwee** [comment]
We could add p-values for the correlation. The correlation is computed for the gene matrix X and gene set matrix gsetX. There is a function in playbase for that playbase::cor.pvalue()

**Comment by mauromiguelm** [comment]
Definitely, what Ivo mentioned will fix the issue!

**Comment by ivokwee** [comment]
archiving as stale issue.
