### ISSUE TITLE
When user is logged in and receives a dataset, automatically notify user

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#624]
**problem:** if the user is logged in and receives a shared dataset, he will have to log out and log in again to be able to see the share dataset.

**solution:** detect new datasets and notify user as soon as a new share dataset is received.

**Comment by ESCRI11** [comment]
Easy, although not most efficient way would be using `reactivePoll`.

**Comment by mauromiguelm** [comment]
needed some refactoring but I incorporated reactivePoll as a substitute to reactive logic ;)
