### ISSUE TITLE
Download each plot in grid separately

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#627]
**Problem:** for many grid plots, we can only download all grid at once. Sometimes user only wants one plot, so we should consider allowing download of a single plot in a grid separately.

Example:
<img width="1074" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/73dfa8d8-368e-4757-a8c3-c0871703577e">

**Comment by ivokwee** [comment]
For a single gene, I think this can be done in the dataview module. Are you sure about this? I am not aware people asking that for this particular plot. I think this issue is also related to rendering plotly panels using html/bootstrap rather than plotly::subplot().

**Comment by mauromiguelm** [comment]
This comes from user feedback, see https://docs.google.com/spreadsheets/d/1ybTkHo1zDTPe-dT-nF5To0inR8xbRwFlRm751pWa5Ww/edit#gid=545946193&range=28:28
