### ISSUE TITLE
Add custom name to the plots when downloaded

### ISSUE THREAD

**Issue by ShaliniPandurangan** [bigomics/omicsplayground#632]
When plots or data is downloaded using the download button, they have the same name. 
E.g.: 'plot.png'  when png files are downloaded. 
It would be nice to have custom names to the plots or data.
E.g.:  expression_plot_top_genes.png when expression plot is downloaded. 
  

  
  
  
<details> <summary><strong>Session Info</strong></summary>

```r
```
</details>

**Comment by ivokwee** [comment]
how do you get the names? perhaps you can use the NS() to get unique names.
