### ISSUE TITLE
[JS] Move inline javascript to .js file

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#64]
All inline javascript should be moved to separate .js files. Improves code readability and makes the JavaScript code easier to maintain.
Might also be useful to create multiple .js files (for example: firebase.js, userAuthentication.js, customInteractions.js ...)

**Comment by JohnCoene** [comment]
We're going to use a pre-processor (e.g.: [packer](https://packer.john-coene.com/)) for this, given the amount of JavaScript there will eventually be in the app support all functionalities, multiple files won't be manageable.
