### ISSUE TITLE
Pgx check for valid feature names

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#652]
In dataset 76370e442 we had invalid features whcih crashed pgx.

We need to build a fast pgx check to prevent user from computing pgx when feature names (genes, proteins...) are invalid.

The valid features are listed here https://omicsplayground.readthedocs.io/en/latest/dataprep/counts.html

**Comment by ESCRI11** [comment]
@mauromiguelm Is this grep pattern OK to check for valid feature names? Could you provide some feature names examples that crash the application?

```
ensembl_pattern <- "^ENSG[0-9]+$"
ensembltran_pattern <- "^ENST[0-9]+$"
unigene_pattern <- "^Hs\\.[0-9]+$"
refseq_pattern <- "^NM_[0-9]+$"
accnum_pattern <- "^[A-Z][0-9]{5}$"
uniprot_pattern <- "^\\w{6}$"
symbol_pattern <- "^[A-Za-z0-9-]+$"
```

**Comment by mauromiguelm** [comment]
this will be re-done in multi-species, if no match is found in biomart probe IDs, we have to return an error in upload module... I will keep it open as this is important

**Comment by ivokwee** [comment]
archiving as stale issue.
