### ISSUE TITLE
[R] Refactor project structure into ui.R / server.R / global.R

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#67]
With an application as large as this, it is worth splitting out the app.R file into separate ui.R and server.R files. The UI and server logic are two separate pieces of functionality and are easier to deal with in separate files.

- [x] The creation of constants in the app.R and app-init.R files can be moved to the global.R file. This file automatically gets sourced before anything else, so these variables will always be created.
- [x] The global.R file doesn't need to be sourced explicitly
- [x] Any function definitions can be moved to a utils.R file.

**Comment by ivokwee** [comment]
Reopened. We have a wrapper run_application()  around shiny::shinyApp to add some endpoint handlers for the error/crash log. See in your file global.R (and originally app.R). If we invoke runApp() that uses ui.R and server.R I believe the handlerManager is not invoked. 

Not sure if we can move the handlerManager code into server.R (but outside the server() function). Please discuss with John. He implemented the log handler.

**Comment by stefanreifenberg** [comment]
Fixed it. Loghandler is writing logs again. @JohnCoene close the issue if you are ok with it. Code is in my last commit in the develop branch
![Screenshot 2022-03-01 at 17 07 00](https://user-images.githubusercontent.com/15939539/156205218-0fe2b0da-f5ec-4899-9d09-ba3d524444ea.png)

**Comment by JohnCoene** [comment]
Works for me, thanks!
