### ISSUE TITLE
Upload New page is not responsive

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#676]
The only page I found which is not responsive to screen size is the Upload New page. All other pages seem to fit perfectly on the screen regardless of zoom, whereas the Upload New page goes too long off the screen even on 100% standard zoom on my computer. I am attaching an example of how the load dataset page looks like on high zoom (still fits the page) vs the upload new page - just for reference.

I believe this issue is caused by the data upload section, as we should have no trouble getting the plotmodules to be responsive.

<img width="1440" alt="Screen Shot 2023-09-08 at 12 15 47 PM" src="https://github.com/bigomics/omicsplayground/assets/13004360/1edbdb32-cd8d-4d85-8c15-121d271e6678">

<img width="1440" alt="Screen Shot 2023-09-08 at 12 16 06 PM" src="https://github.com/bigomics/omicsplayground/assets/13004360/e8a802eb-ff3a-4dc4-93d2-94156d1890b5">

**Comment by mauromiguelm** [comment]
WGCNA as well: we should use the same layout structure as other boards - should be easy to fix

https://github.com/bigomics/omicsplayground/blob/master/tests/testthat/_snaps/linux-4.1/board-values/wgcna.png
