### ISSUE TITLE
Clustering > Samples > Heatmap > Clustered Heatmap figure is cropped when downloaded

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#677]
**Problem:** The downloaded images (png, pdf...) of clustersamples-splitmap-pltmod cannot be properly sided, even when we change height and width settings.

**dataset:** example data

[clustersamples-splitmap-pltmod (8).pdf](https://github.com/bigomics/omicsplayground/files/12559675/clustersamples-splitmap-pltmod.8.pdf)
[clustersamples-splitmap-pltmod (7).pdf](https://github.com/bigomics/omicsplayground/files/12559676/clustersamples-splitmap-pltmod.7.pdf)
[clustersamples-splitmap-pltmod (6).pdf](https://github.com/bigomics/omicsplayground/files/12559677/clustersamples-splitmap-pltmod.6.pdf)
[clustersamples-splitmap-pltmod (9).pdf](https://github.com/bigomics/omicsplayground/files/12559678/clustersamples-splitmap-pltmod.9.pdf)

**Comment by ESCRI11** [comment]
@mauromiguelm Does this look good?
[clustersamples-splitmap-pltmod.pdf](https://github.com/bigomics/omicsplayground/files/12602121/clustersamples-splitmap-pltmod.pdf)

**Comment by mauromiguelm** [comment]
Hi Xavier, I think we still need some extra left space for title.. and with bigger datasets (higher number of contrasts and samples), will this padding be maintained? It happens sometimes that it works on small datasets, but not on big ones

**Comment by ESCRI11** [comment]
I can add more padding to the left. It should be the same for all datasets, I will test on a bigger one to make sure
