### ISSUE TITLE
data-preview not saving matrix if we upload them sequentially

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#700]
if I upload counts, click ok, then upload samples, click ok, then the counts matrix will be lost in data preview

also, the error messages are strange in this case. The error message should only be triggered when the necessary matrices are upload.

Eg. sample-contrast check should only be run if we have both matrices

**Comment by mauromiguelm** [comment]
one more thing: if the user upload samples and counts, he should be directed to the contrast building module!

**Comment by mauromiguelm** [comment]
this has to be worked in dev-multi-species

**Comment by ESCRI11** [comment]
@mauromiguelm Pretty much everything you wanted is solved on [41b2ff7](https://github.com/bigomics/omicsplayground/commit/41b2ff74c40efc6eab8f977bcef23975742b6cea). The only thing I have not implemented is "one more thing: if the user upload samples and counts, he should be directed to the contrast building module!"; the reason being when we upload samples and counts the contrast building tab appears, I see no need to automatically redirect the user, maybe he wants to upload the contrasts.csv afterwards sequentially.

**Comment by mauromiguelm** [comment]
Hi @ESCRI11, the user can always click ok and got to comparisons module, right?

Then maybe we write something that comparisons file is optional, and direct the user to that board, in case samples vs counts check passes?

**Comment by ESCRI11** [comment]
@mauromiguelm Comparisons module is activated when samples and counts are uploaded

**Comment by ESCRI11** [comment]
- [ ] Add delete uploaded files

**Comment by mauromiguelm** [comment]
obsolete, this will be redone in the new upload module
