### ISSUE TITLE
give more information about what type of statistical method we have at Upload > compute > options

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#711]
it would be nice to classify the methods by type, or even add tooltip explaining what they do

**Comment by ESCRI11** [comment]
@mauromiguelm Classification by type sounds reasonable. For information itself, wouldn't it make more sense to describe them on the readthedocs instead of a tooltip?

**Comment by mauromiguelm** [comment]
I dont know, maybe have a rough classification by statistical type would be nice, as we have ~8 methods now and its difficult for user to know which to choose.

Recommendation from Ivo is to select at least two from each "type".. @ivokwee can you describe this in more detail?
