### ISSUE TITLE
bring back "show legends" button from settings tab to the front page, to show plot captions

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#714]
Today is very difficult to find that button, we should bring it back to the front page.

Nick tried to place it under settings, to have more settings available, but its too hidden. That means users dont get the extra info that comes with plot caption.

**Comment by mauromiguelm** [comment]
ivo's suggestion: move app settings as a drop down in the navbar, you hover, the drop down appear, adn then you see the options for beta fatures, show captions...

**Comment by ESCRI11** [comment]
@mauromiguelm Something similar to this?

https://github.com/bigomics/omicsplayground/assets/10220503/2d860238-a37c-4f89-bdf6-787eebcdd3e6

**Comment by ivokwee** [comment]
very nice. it's a good new way of showing the buttons more prominently. Will you put it in BigDash? please merge if it works. As you commented, we should not overdo it with hundreds of buttons but few important ones are good.
