### ISSUE TITLE
date on pgx object is sometimes incorrect due to time zone

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#724]
I calculated example data for some tests, and locally it shows 25.10.2023 and in Omics Playground 24.10.2023

local
<img width="611" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/8e2c7cb4-4904-4956-aea1-ae2afb15b8da">

OPG
<img width="484" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/924f9feb-4c85-4b81-bd97-bd0ed402ca3f">

We are probably calculating in GMT, whereas we should use local time (CET, EDT, EST...)

**Comment by ESCRI11** [comment]
@mauromiguelm https://github.com/bigomics/omicsplayground/blob/master/components/board.upload/R/upload_module_computepgx.R#L458 This is the date appended to the pgx file, so I do not see where this could go wrong. This date should not necessarly match the one shown by file explorer

**Comment by mauromiguelm** [comment]
sys.time is in gmt (?), so if I compute a pgx at 4pm local time and I am gmt +6, then pgx date will be yesterday

**Comment by ESCRI11** [comment]
Not really, from the R documentation: "Sys.time and Sys.Date returns the system's idea of the current date with and without time."
