### ISSUE TITLE
Problem with the expression table in the Multi-species beta platform (v3.2.28-master231025)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#732]
For some reason, I am no longer able to see the coloured red and blue bars in the differential expression table in the latest release of the multispecies platform:

![image](https://github.com/bigomics/omicsplayground/assets/85561624/d6888ffd-e249-40ed-8c9f-21d4f543b09b)

I could replicate the error with different datasets.

Below what it normally should look like for the same dataset used above:

![image](https://github.com/bigomics/omicsplayground/assets/85561624/813734bd-0da3-4dc7-b1cb-83d5cc3d7ead)

**Comment by ESCRI11** [comment]
Issue closed on https://github.com/bigomics/omicsplayground/pull/726/commits/22cf4fbdafb20886fa95152849ea1e7315d2f872
