### ISSUE TITLE
contrasts with one column and zero columns crash platform

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#762]
## zero columns contrasts

``` R
Warning: Error in <-: length of 'dimnames' [1] not equal to array extent
  76: h
  75: .handleSimpleError
  74: rownames<-
  73: playbase::read.as_matrix
  72: observe
  71: <observer:observeEvent(input$upload_files)>
  70: valueFunc
  69: ..stacktraceon..
  68: contextFunc
```

## one column contrasts

- data is good
<img width="368" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/78daa6f4-501a-4e34-90c8-930113f1d64e">

- but somehow the makecontrasts cannot find the samples
<img width="1114" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/3073ad77-e786-403f-a788-d5c32ea4e67b">

## data to reproduce
[contrasts_zerocols.csv](https://github.com/bigomics/omicsplayground/files/13435933/contrasts_zerocols.csv)
[contrasts_one_contrasts.csv](https://github.com/bigomics/omicsplayground/files/13435934/contrasts_one_contrasts.csv)
[counts.csv](https://github.com/bigomics/omicsplayground/files/13435936/counts.csv)
[samples.csv](https://github.com/bigomics/omicsplayground/files/13435937/samples.csv)

**Comment by ivokwee** [comment]
I think resolved in latest commit playbase
