### ISSUE TITLE
Multi-species: GSEA plots look very different human datasets

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#770]
Started testing the multispecies beta and I immediately noticed some major issues with the GSEA plots. For example in version v3.2.34. I get this nice smooth plot for the exact same dataset:

![image](https://github.com/bigomics/omicsplayground/assets/85561624/615ff615-7b75-438a-8fb9-17b90e0e25e4)

But in the multispecies beta, I get this horror show:

![image](https://github.com/bigomics/omicsplayground/assets/85561624/7df55d08-d8dc-46b4-b251-311198d5bee9)

**Comment by mauromiguelm** [comment]
Axel was using old version of multi-species - closing the issue!
