### ISSUE TITLE
Multi-Species: Cell profiling looks disabled or non-functional

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#772]
The cell profiling module does not show certain plots of shows error messages:

![image](https://github.com/bigomics/omicsplayground/assets/85561624/a13c0572-a1ba-457c-b37e-8b930105cb01)

![image](https://github.com/bigomics/omicsplayground/assets/85561624/33b364a8-027b-4ecd-8c25-8f7c2e06f2db)

![image](https://github.com/bigomics/omicsplayground/assets/85561624/f503ab72-3e43-463f-9f54-55a244050eb3)

**Comment by phisanti** [comment]
@AxelBigOmics For which dataset is this?
