### ISSUE TITLE
C elegans dataset: test signatures has unnamed features

### ISSUE THREAD

**Issue by phisanti** [bigomics/omicsplayground#776]
When loading teh C elgans dataset (GSE240425) and compute with no gene symbol collapse

![Screenshot 2023-12-01 140446](https://github.com/bigomics/omicsplayground/assets/33370667/3416d293-afe0-4367-839b-423a0eb82114)

**Comment by mauromiguelm** [comment]
Hi @phisanti 

no features are highlighted in volcano when using dataset of collapsed = FALSE
<img width="1261" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/c978b9db-0d24-4276-a3b0-d1a6a20b2ddc">

**Comment by mauromiguelm** [comment]
closed in #782
