### ISSUE TITLE
Problem with "Similar experiments" module and database size

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#792]
I am experiencing a problem most likely linked to the amount of datasets I have on the platform (149). Every time I try to do a "similar experiments" analysis, the platform crashes with the blank screen below, though you can make out the following error message:

_"Index exceeds HDF5 array dimensions"._

This applies to the latest docker version I have available (v3.2.29.9000-master231102)

![image](https://github.com/bigomics/omicsplayground/assets/85561624/a5be4d9a-aca6-47a9-991e-19a369337bc9)

**Comment by ivokwee** [comment]
You can delete all datasets-* fiiles in your folder and see if it occurs again. Before deleteing, please make a zip file and send it to us, so we can check the problem.

**Comment by mauromiguelm** [comment]
old issue not reported anymore, likely fixed
