### ISSUE TITLE
compare datasets foldchange scatterplot is not rendering well with multiple comparison

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#795]
The "compare datasets" foldchange scatterplot is not rendering well with multiple comparison. See below. WIth three comparison for dataset1 and three comparisons for dataset2, it should give a 3x3 scatterplot pairs matrix. In the new v3 plot it only shows 1 plot and the axis are showing contrast 1 and 2 for the first dataset only. The cumulative foldchange should show the three comparison in different colors, not just summing up.

![image](https://github.com/bigomics/omicsplayground/assets/19613146/7cf5b500-1738-4155-96c7-4d5852934690)

![image](https://github.com/bigomics/omicsplayground/assets/19613146/93238c04-8102-4ed4-8c2e-611bf62776ba)

**Comment by Kstead** [comment]
Isnt that replicating the function of the Compare signatures Pairwise scatter tab?
