### ISSUE TITLE
UX suggestion for Compare datasets function

### ISSUE THREAD

**Issue by Kstead** [bigomics/omicsplayground#796]
<details> <summary><strong>Session Info</strong></summary>
  
```r

```
</details>

Compare tab >  compare datasets tab > fold change tab is very helpful but the comparisons are calculated live which makes selecting what contrasts very difficult as the platform hangs for the calculation while scrolling down through the available contrasts. Would be better to select and have a [compute] button function like the biomarkers tab

**Comment by ivokwee** [comment]
done in upcoming v3.5.0
