### ISSUE TITLE
crash on compare signatures > singature clustering > contrast correlation

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#805]
![image](https://github.com/bigomics/omicsplayground/assets/28757711/1e48c8da-bd9a-49c7-8a2f-720cc298fa20)

**Comment by phisanti** [comment]
Cannot reproduce. Does it also happens to you? 
![Uploading image.png…]()

**Comment by ESCRI11** [comment]
Same here, works good on latest playbase + master OPG
