### ISSUE TITLE
similar experiments > FC correlation > FC scatter plots crash

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#806]
![image](https://github.com/bigomics/omicsplayground/assets/28757711/75069c1c-a612-457b-aee0-f324e2975acb)
[20231214_yeast_gmt.zip](https://github.com/bigomics/omicsplayground/files/13674863/20231214_yeast_gmt.zip)

**Comment by ESCRI11** [comment]
@mauromiguelm Latest playbase and master branch works good.

![image](https://github.com/bigomics/omicsplayground/assets/10220503/a0b5aa4a-a7d6-4e72-81b5-f6206c2d25cf)

**Comment by phisanti** [comment]
Currently, I cannot reproduce in my local device.
![image](https://github.com/bigomics/omicsplayground/assets/33370667/5215ec82-dea2-40ef-a003-05d7f4150e62)
