### ISSUE TITLE
Drug Connectivity tab unavailable for C. elegans (v3.3.0-beta10-master231214)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#818]
I've been working on a C. elegans dataset on the effects of various benzimidazole derivatives on the worm and even if I select the "drugs connectivity" option in the "Compute" panel, the corresponding module is missing when I open the dataset.

I am attaching the input files I used if you want to recreate the issue.

[counts.csv](https://github.com/bigomics/omicsplayground/files/13702412/counts.csv)
[samples.csv](https://github.com/bigomics/omicsplayground/files/13702413/samples.csv)
[contrasts.csv](https://github.com/bigomics/omicsplayground/files/13702424/contrasts.csv)

**Comment by phisanti** [comment]
I think this is an issue at the level of playbase/pgx.computePGX. I will try to look at it this week.
