### ISSUE TITLE
Error in loadNamespace(x) : there is no package called ‘playbase’

### ISSUE THREAD

**Issue by histon1881** [bigomics/omicsplayground#833]
Hi, I wanted to make it work from the source code long time ago to find a few bugs and understand some conflicts in my pathway analysis outcomes but there were many gaps in the readme file so neither I nor my senior software engineer friends couldn't succeed at that time and I gave up. Now, I tried again by my own as a biologist but decided to write my challenges in this platform one by one here. The first issue is "not to find playbase package."

In R environment, I installed the playbase and other two components in a way written in readme document.

>getwd()
[1] "/home/username_X_"

>remotes::install_github('bigomics/playbase')
>remotes::install_github('bigomics/bigdash')
>remotes::install_github('bigomics/bigLoaders')

It was succesfully installed in the following directory:
‘/home/username_X_/R/x86_64-pc-linux-gnu-library/4.3’

I have also installed python interpreter
>install.packages("reticulate")
>reticulate::install_miniconda()

Then in the command line, I succesfully installed the git clone by typing:
>git clone https://github.com/bigomics/omicsplayground.git

After that, this was also succussful.

username_X_@username_X_-VirtualBox:~$cd omicsplayground

username_X_@username_X_-VirtualBox:~/omicsplayground$Rscript dev/requirements.R

By the way it also says "As option, you can run the following command in the **build/ folder** to build the datasets:" however there is no build folder in my linux OS after those steps. There is only one folder after installing all of them that is "Home/R/x86_64-pc-linux-gnu-library/4.3/pkgbuild". Do you mean this pkgbuild folder?

Anyway I continued with
username_X_@username_X_-VirtualBox:~/omicsplayground$ make run
........................................................
source all called from wd = /home/username_X_/omicsplayground/components

Note: sourcing all code...

done! (sourcing all code)

************************************************

************* PARSING OPTIONS ******************

************************************************

Error in loadNamespace(x) : there is no package called ‘playbase’

Calls: source ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart

Execution halted

make: *** [Makefile:5: run] Error 1
************************************
Could you tell me why it cannot find playbase package? I followed the readme file but do I miss anything? Thanks for your time.

**Comment by histon1881** [comment]
I have solved that problem too. But there is another problem now. It says it sent a login code to my email address but I don't receive any email and I cannot use the platform. Here are the details. By the way, are you sure that this is really open source project? I'm asking because it looks like pushing me to use the website based version for many months without letting me understand how it works in the background. The idea is great to make this platform but I cannot use this platform for a future research paper of mine or any thesis of mine when I cannot fix the problems I found at the end of my analysis output! I must see how the data is handled and be able to customize it to use in my research and fix the problems in the analysis! Thanks for your time.

make run

Rscript dev/sass.R

Rscript dev/create_source_all.R

Creating SourceAll file: components/00SourceAll.R

new version -&gt; v3.3.0-beta12.9001-master231228

echo &quot;v3.3.0-beta12.9001&quot;&quot;-&quot;`git rev-parse --abbrev-ref HEAD`&quot;&quot;`date +%y%m%d|sed &apos;s/\ //g&apos;` &gt; VERSION

find . -name &apos;LOCK*&apos; -exec rm {} \;

Rscript dev/run_app.R



  ___            _          ____  _                                              _ 

 / _ \ _ __ ___ (_) ___ ___|  _ \| | __ _ _   _  __ _ _ __ ___  _   _ _ __    __| |

| | | | &apos;_ ` _ \| |/ __/ __| |_) | |/ _` | | | |/ _` | &apos;__/ _ \| | | | &apos;_ \  / _` |

| |_| | | | | | | | (__\__ \  __/| | (_| | |_| | (_| | | | (_) | |_| | | | || (_| |

 \___/|_| |_| |_|_|\___|___/_|   |_|\__,_|\__, |\__, |_|  \___/ \__,_|_| |_| \__,_|

                                          |___/ |___/                              


[GLOBAL] reading global.R ...

&gt;&gt;&gt;&gt;&gt; working directory = /home/username_X_/omicsplayground/components/app/R

&gt;&gt;&gt;&gt;&gt; LOADING INITIAL LIBS

***********************************************

***** RUNTIME ENVIRONMENT VARIABLES ***********

***********************************************

SHINYPROXY_USERNAME = 

SHINYPROXY_USERGROUPS = 

PLAYGROUND_AUTHENTICATION = 

PLAYGROUND_USERNAME = 



***********************************************

*********** SETTING GLOBAL VARIABLES **********

***********************************************

OPG =/home/username_X_/omicsplayground

FILES =/home/username_X_/omicsplayground/lib

FILESX =/home/username_X_/omicsplayground/libx

PGX.DIR =/home/username_X_/omicsplayground/data

APPDIR =/home/username_X_/omicsplayground/components/app/R

SHINYPROXY = FALSE



************************************************

************* SOURCING FUNCTIONS ***************

************************************************

source all called from wd = /home/username_X_/omicsplayground/components

Note: sourcing all code...

done! (sourcing all code)



************************************************

************* PARSING OPTIONS ******************

************************************************



TITLE 	=  Omics Playground

AUTHENTICATION 	=  login-code

ALLOW_NEW_USERS 	=  TRUE

ALLOW_PERSONAL_EMAIL 	=  FALSE

USE_CREDENTIALS 	=  FALSE

BLOCKED_DOMAIN 	=  bigomics.com|massdynamics.com|pluto.bio|rosalind.bio

ENABLE_CHIRP 	=  TRUE

ENABLE_DELETE 	=  TRUE

ENABLE_PGX_DOWNLOAD 	=  TRUE

ENABLE_PUBLIC_SHARE 	=  TRUE

ENABLE_UPLOAD 	=  TRUE

ENABLE_USERDIR 	=  TRUE

ENABLE_USER_SHARE 	=  TRUE

ENABLE_USER_LOCK 	=  TRUE

ENABLE_HEARTBEAT 	=  TRUE

ENABLE_INACTIVITY 	=  TRUE

MAX_DATASETS 	=  25

MAX_SAMPLES 	=  1000

MAX_COMPARISONS 	=  20

MAX_GENES 	=  20000

MAX_GENESETS 	=  5000

MAX_SHARED_QUEUE 	=  3

MAX_SESSIONS 	=  2

TIMEOUT 	=  0

WATERMARK 	=  TRUE

APACHE_COOKIE_PATH 	=  /app/omicsplayground/









=================================================================

=================== GLOBAL INIT DONE ============================

=================================================================







[GLOBAL] global init time = 0.9605 secs

Warning messages:

1: replacing previous import ‘data.table::first’ by ‘dplyr::first’ when loading ‘playbase’ 

2: replacing previous import ‘data.table::last’ by ‘dplyr::last’ when loading ‘playbase’ 

3: replacing previous import ‘data.table::between’ by ‘dplyr::between’ when loading ‘playbase’ 

4: replacing previous import ‘data.table::transpose’ by ‘purrr::transpose’ when loading ‘playbase’ 



Listening on http://0.0.0.0:3838

Read 1 item

[INFO][2023-12-28 23:21:29][520MB] --- [ui.R] &gt;&gt;&gt; creating UI



======================================================

======================= UI ===========================

======================================================



Read 1 item

Warning: analytics and firestore arguments are deprecated

[DBUG][2023-12-28 23:21:29][528MB] --- [ui.R] sum.enabled =  22

[DBUG][2023-12-28 23:21:29][528MB] --- [ui.R] names.enabled =  welcome load upload dataview clustersamples clusterfeatures diffexpr enrich isect pathway wordcloud drug sig cell corr bio cmap wgcna tcga comp user pcsf

[INFO][2023-12-28 23:21:29][528MB] --- [ui.R] creating sidebar menu

[INFO][2023-12-28 23:21:30][629MB] --- [ui.R] &lt;&lt;&lt; finished UI!

[INFO][2023-12-28 23:21:48][649MB] --- [ui.R] &gt;&gt;&gt; creating SERVER



===========================================================

======================== SERVER ===========================

===========================================================



Read 1 item

[INFO][2023-12-28 23:21:48][649MB] --- [SERVER] getwd =  /home/username_X_/omicsplayground/components/app/R

[INFO][2023-12-28 23:21:48][649MB] --- [SERVER] SESSION =  fd71abb53e976de5714855bcbcb91a9e

[AuthenticationModule] &gt;&gt;&gt;&gt; using LoginCode authentication &lt;&lt;&lt;&lt;

Warning in module(childScope$input, childScope$output, childScope, ...) :

  [LoginCodeAuthenticationModule] ERROR : missing mail_creds file!!!

Read 1 item

[DBUG][2023-12-28 23:21:48][649MB] --- [LoginCodeAuthenticationModule:sendLoginCode] no cookies found

[DBUG][2023-12-28 23:21:49][649MB] --- [UserProfileBoard] &gt;&gt;&gt; initializing UserBoard...

[DBUG][2023-12-28 23:21:49][649MB] --- [UserSettingsBoard] &gt;&gt;&gt; initializing User Settings...

[INFO][2023-12-28 23:21:52][650MB] --- [SERVER] ENABLE_USER_LOCK =  TRUE

*********************************************************

***** new session  fd71abb53e976de5714855bcbcb91a9e *****

*********************************************************

[DBUG][2023-12-28 23:21:52][650MB] --- [SERVER] number of active sessions =  1

[DBUG][2023-12-28 23:21:52][650MB] --- [MAIN] showing startup modal

[INFO][2023-12-28 23:21:52][650MB] --- [SERVER] server.init_time =  3.5414   secs

[INFO][2023-12-28 23:21:52][650MB] --- [SERVER] total lapse time =  26.5602   secs

Warning in mapply(children, flex, FUN = function(el, flexValue) { :

  longer argument not a multiple of length of shorter

[DBUG][2023-12-28 23:22:08][650MB] --- [LoginCodeAuthenticationModule] initiating sending code

[INFO][2023-12-28 23:22:08][650MB] --- [LoginCodeAuthenticationModule] sending login code CZYE-EUBC-EJSF to username_X_@XX.XX.XX

Warning in sendLoginCode(login_email, login_code, mail_creds = mail_creds) :

  [LoginCodeAuthenticationModule:sendLoginCode] WARNING: no mail_creds file

Read 1 item</pre>

**Comment by zitoa** [comment]
Hi @histon1881:  we're aware of this. Please note you can find your login code in your output above: CZYE-EUBC-EJSF.

Alternatively, you could fix the issue by editing the file etc/OPTIONS, enabling AUTHENTICATION=none (line 2) and disabling AUTHENTICATION=login-code (line 5).

Thanks,
Antonino

**Comment by histon1881** [comment]
Hi Zitoa, many thanks, I had found a way to bypass the authentication by deleting some authentication lines but l couldn't realize the login code in my output. Many thanks for making me realize it and showing me another editing option.
Happy new year...
