### ISSUE TITLE
Issue with "compare datasets" (v3.3.0-beta9-master231212)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#834]
I'm getting an error with any of the datasets I use, where the individual gene plots are not displayed and I get an arguments length error message. I repeated the error across multiple datasets.

![image](https://github.com/bigomics/omicsplayground/assets/85561624/32625c12-46fd-4c75-803b-a8f2439b8c9e)

**Comment by ESCRI11** [comment]
Solved on beta12
