### ISSUE TITLE
[R] Refactor active binding (%<a-%) from the pryr package

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#84]
- Active binding (%<a-% from pryr package) is used a lot in assigning the plot object to the
  plotModule, shiny reactive environment keeps track of changes in reactive objects by
  design.

- Example: shiny/boards/DrugConnectivityBoard.R:
  Line 176: dsea_enplots.RENDER %<a-% reactive({
  Can be just dsea_enplots.RENDER<- reactive({

- I suspect this is done to be able to pass the object to the module, but it can be passed to
   the module using reactive(dsea_enplots.RENDER()) Instead of just dsea_enplots.RENDER

**Comment by stefanreifenberg** [comment]
plots are now showing up in the modal without the pryr package:
<img width="1433" alt="Screenshot 2022-03-04 at 10 46 02" src="https://user-images.githubusercontent.com/15939539/156740934-694c9c06-ea22-466c-b71f-aeee93613b7b.png">

**Comment by ivokwee** [comment]
Wow. that is great. Can you explain what was wrong and how you solved it? Then we can probably close the issue.
