### ISSUE TITLE
[R] Remove unused libraries

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#85]
1. Use NCmisc library to get all the packages
    and functions loaded on memory
2. Then iterate over all the .R files to find all
    lines where library or require is called
3. Do some cleanup manually
4. Compare the 2 lists
  a. One list with loaded library names
  b. Other list with used library name
<img width="1210" alt="Screenshot 2022-02-21 at 11 49 16" src="https://user-images.githubusercontent.com/15939539/154940620-e3d8849a-8517-4cf1-8e46-d42bd5e585a7.png">
s

**Comment by marcosci** [comment]
limma is used for example, but seems to be quite antique:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/10864574/162422013-74d5725e-274e-445b-9720-752ea7d771e6.png">
