### ISSUE TITLE
dataview > sample information: add option for phenotype correlation

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#883]
How can you choose phenotype correlation for a subset? E.G for cell types?

**Comment by zitoa** [comment]
Hi Mauro, i am looking at it...

**Comment by zitoa** [comment]
@mauromiguelm is this question linked to a specific downstream processing? If there's a dataset linked to this question can you pls share thanks.

**Comment by zitoa** [comment]
One way could be adding the option of filtering the metadata (samples.csv) and run correlation on that subset

**Comment by ivokwee** [comment]
Unclear. Closing stale issue.
