### ISSUE TITLE
Custom gene list not shown in plots under compare datasets (v3.3.0-beta18-master240301)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#897]
A user just highlighted that the custom gene list is not being correctly visualised in the plots under the "Compare datasets" module:

![image](https://github.com/bigomics/omicsplayground/assets/85561624/523ea65f-4167-4edc-8030-d001dece3f0b)

Can you please take a look and fix as needed?

**Comment by ESCRI11** [comment]
Solved on #911
