### ISSUE TITLE
Compare datasets > Fold change > Highlight genes > Custom: Genes from custom GMT do not appear in results

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#898]
Compare datasets > Fold change > Highlight genes > Custom: Genes from custom GMT do not appear in results

In a pgx with added custom gmt added, we should make sure users can query those genes in compare datasets

**Comment by profundity** [comment]
Still does not happen.  My custom geneset as .gmt directly from MSigDB does not show up.
