### ISSUE TITLE
Upload Contrast: Handling numerical sample phenotypes

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#913]
- can we dichotomize numerical phenotype at the time of upload (low, medium, high...?)
- today we have numerical data being used as factor, which is not ideal

**Comment by mauromiguelm** [comment]
this will likely require significant amount of work and refactoring

**Comment by ivokwee** [comment]
I think it is already done in the GUI, splitting to "high" and "low". However not done in createPGX. UI and message could be improved. Closing issue.
