### ISSUE TITLE
Venn Diagram plotting error

### ISSUE THREAD

**Issue by Kstead** [bigomics/omicsplayground#914]
<details> <summary><strong>Session Info</strong></summary>
  
```r

```
</details>
Compare - Compare signatures - pairwise scatter Venn diagram - "Error: there is no package called 'sf' "

**Comment by mauromiguelm** [comment]
> **Session Info**
> Compare - Compare signatures - pairwise scatter Venn diagram - "Error: there is no package called 'sf' "

Dear Ken, I just submit a fix for this issue, we will run a few more tests and submit a fix in the next days.

Sorry for the disruption!
