### ISSUE TITLE
playgroundV3.3.4-master240424 Carsh

### ISSUE THREAD

**Issue by DaliJarboui** [bigomics/omicsplayground#927]
Dear omics playground team, 
somehow the new docker image of playground crashes with the error below. 
I run before the same files with older versions and was no problem at all, it crashes with every datasets I load (all were analyzed before no problem)
organism was specified properly, somehow most of the crashes are related to organism (it crashes with mouse, Rat or human datasets although the organism is specified correctly).
thanks for your help

below the latest crash report 
 Error:
[processx.1:stderr] [create PGX process] : starting process
[processx.1:stderr] [createPGX] check logarithm/linear...
[processx.1:stderr] [createPGX] input assumed logarithm: undo-ing logarithm
[processx.1:stderr] [createPGX] no XXL values detected
[processx.1:stderr] [mergeDuplicateFeatures] 42 duplicated rownames: summing rows (in counts).
[processx.1:stderr] [createPGX] removing outliers samples
[processx.1:stderr] [createPGX] scaling counts...
[processx.1:stderr] [createPGX:autoscale] WARNING: too large total counts. Scaling down to 10e6 reads.
[processx.1:stderr] [createPGX:autoscale] count_multiplier= 10000
[processx.1:stderr] [createPGX] creating log-expression matrix X...
[processx.1:stderr] [createPGX] SKIPPING NORMALIZATION!
[processx.1:stderr] [createPGX] conforming matrices...
[processx.1:stderr] [createPGX] creating pgx object...
[processx.1:stderr] [createPGX] annotating genes
[processx.1:stderr] [ngs.getGeneAnnotation] organism = Human
[processx.1:stderr] [getGeneAnnotation] >>> annotating genes using ORGDB libraries
[processx.1:stderr]
[processx.1:stderr] Error in ngs.getGeneAnnotation(pgx = pgx, probes = probes, annot_table = annot_table, :
[processx.1:stderr] probe_type is NULL
[processx.1:stderr] Calls: -> pgx.addGeneAnnotation -> ngs.getGeneAnnotation
[processx.1:stderr] In addition: Warning messages:
[processx.1:stderr] 1: replacing previous import ‘data.table::last’ by ‘dplyr::last’ when loading ‘playbase’
[processx.1:stderr] 2: replacing previous import ‘data.table::first’ by ‘dplyr::first’ when loading ‘playbase’
[processx.1:stderr] 3: replacing previous import ‘data.table::between’ by ‘dplyr::between’ when loading ‘playbase’
[processx.1:stderr] 4: replacing previous import ‘data.table::transpose’ by ‘purrr::transpose’ when loading ‘playbase’
[processx.1:stderr] 5: In guess_organism(rownames(counts)) :
[processx.1:stderr] [guess_organism] Could not auto-detect organism.
[processx.1:stderr] 6: In guess_probetype(probes, for.biomart = FALSE) :
[processx.1:stderr] [guess_probetype] ERROR : unsupported probe_type: GENEBANK
[processx.1:stderr] 7: In guess_probetype(probes, for.biomart = FALSE) :
[processx.1:stderr] [guess_probetype] keytypes available: ENSEMBL ENSEMBLPROT ENSEMBLTRANS ENTREZID REFSEQ SYMBOL UNIPROT
[processx.1:stderr] Execution halted

**Comment by mauromiguelm** [comment]
Dear User,

Thanks for opening the issue, this is due to your rownames of counts - features names - being GENEBANK, which is not accepted. We recommend using ENSEMBL or one of the supported probe types.

I cannot provide more information than this just based on this error message; If you want we can have a more in depth look in your counts file, feel free to contact us via [support@bigomics.ch](url).

Kind regards,
Mauro

**Comment by DaliJarboui** [comment]
Actually, my feature names are uniprot entries, sorry forgot to specify that, in older releases, was working fine and never faced that problem. 
I used the exact same matrices I was using before. with no changes. could be that newer versions does not support anymore uniprot entries ? . the problem resolved when I used genes names.
Regards
