### ISSUE TITLE
playbase::guess_organism cannot distinguish between rat and mouse

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#929]
```
[guess_organism] auto-detected organism = MouseRat
Error in if (tolower(organism) != tolower(guess_organism)) { : 
  the condition has length > 1
```

I have seen many crashes so far related to this issue.

**Comment by zitoa** [comment]
@mauromiguelm @ESCRI11   i work on this tomorrow.

**Comment by zitoa** [comment]
@mauromiguelm is this issue already fixed then?

**Comment by mauromiguelm** [comment]
> @mauromiguelm is this issue already fixed then?

Hi @zitoa, yes, there is a PR open, see Development on the right drawer (sidebar).

Cheers,
M
