### ISSUE TITLE
From A. L. (@UAntwerpen.be): drug connectivity

### ISSUE THREAD

**Issue by murodzhon** [bigomics/omicsplayground#94]
Under drug connectivity, when I tried to save the pdf/png, some of the words are cut off (see attachment). 
![A_L_drug_connectivity](https://user-images.githubusercontent.com/20000070/157247164-c5e418a6-ee96-4781-81a4-83699504df94.png)

**Comment by ivokwee** [comment]
True but we cannot accomodate for all long labels. Perhaps truncating at and of label with '...' would be preferred? Like "This is a long lab..."

**Comment by stefanreifenberg** [comment]
cedric might have an idea on this topic

**Comment by ivokwee** [comment]
I don't see a solution. Or perhaps a tooltip when hovering over every bar but that require maybe a plotly based figure.
