### ISSUE TITLE
count matrix template for single cell data analysis

### ISSUE THREAD

**Issue by histon1881** [bigomics/omicsplayground#941]
Hi, 

I was quite happy to explore some bulk RNA seq data but I got a bit challenge for single cell RNA seq data analysis in this platform. I couldn't find a template for count matrix for single cell. For the bulk RNA-seq, it was quite easy; the columns represent samples and raws represent samples, so input was simple. But for RNA-seq, I have multiple count matrices from multiple samples. Do I have to condense all count matrices into one giant count matrix? There is no metadata upload option as an input. How can the platform distinguish different groups' samples and different replicates' samples from one giant single count matrix? 

Thank you very much for your help.

**Comment by zitoa** [comment]
Hello @histon1881 

the metadata file you probably refer to is what we call samples.csv and contrasts.csv.  You can read about it here: https://omicsplayground.readthedocs.io/en/latest/

Please feel free reach out via email to axel.martinelli@bigomics.ch to schedule a free session on how to use the platform. 

Thanks,
Antonino

**Comment by histon1881** [comment]
Hi Zitoa, 

Yes, I had already read the documentation. Thanks for the contact address but the service is only available for the commercial purpose not for the open source part, that was the response once I had received during my email communication with bigomics. Therefore, I write here. But to improve myself in bioinformatics, I try to work on the code itself. I know how the platform suggests the count.csv and sample.csv file. What I say is those count.csv and sample.csv were designed in a way for bulk RNA seq data analysis.

 I still couldn't get the answer my question. Let me express myself with another example. In bulk RNA seq count matrix, sample1, sample2, sample3, sample4, sample5 are columns. Then I choose sample1, sample2 and sample3 in the platfrom as the control group and the sample4, sample5, and sample5 as the treatment group. But in single cell RNA seq, the columns are cell1, cell2, .... cell30.000 for only one sample. In the second samples' count matrix again we have 50.000 columns that are cell1,cell2,....cel50000. If I combine 20 samples, imagine the total number of columns. There is no sample.csv file template which is suitable to distinguish sample1 (cell,1,2,3,....30.000) with sample2(cell1,2,3....50.000). The current sample file templete is also not suitable to distinguish biological replicates. Therefore, I am asking how to create the input files for single cell RNA-seq analysis. The example in the link you have suggested, bigomics has re-analysed GSE72056 from ONLY ONE sample and the current count matrix, sample matrix formats are suitable for single cell analysis from one single sample. It just shows differentially expressed genes between malignant and non-malignant cells from ONE single samples. How can I do it when I have multiple samples?

**Comment by zitoa** [comment]
Hi @histon1881 

To analyze single-cell RNAseq data our platform performs downsampling to 2000 cells. Otherwise we suggest applying a "metacell" approach, where transcriptionally similar cells can be merged into a meta cell to reduce sample size.  With regard to samples.csv file, you can create the file by making unique the column names:  for example sample1.cell1,  sample1.cell2, sample1.cell3,   sample2.cell1, sample2.cell2, sample2.cell3........ Make sure the column names of the counts file match the row names of the samples.csv file.   From there you can also specify the biological replicates (as well as other information) in column in the sample file. 

Thanks,
Antonino

**Comment by zitoa** [comment]
Perfect! Good luck with your analyses.

Antonino
