### ISSUE TITLE
Making changes from the plot editor permanent

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#950]
This is an issue that has been raised regarding the editor for individual plots. Changes that are performed there are lost once users switch back to the default view. I've been told that they would prefer the changes (e.g. changing the samples colours in PCA plots) be maintained in the plots after they exit the editor as well. I personally think that combined with a more simplified editor interface this would be a very welcome improvement in the platform's functionality and ease of use.

**Comment by ivokwee** [comment]
technically very difficults. closing issue.
