### ISSUE TITLE
Cell type profiling not working with mouse dataset (v3.4.0-master240619)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#972]
**dataset:** 7337bf045

I've been trying to get some cell type deconvolution analysis done with a mouse dataset but I'm getting the following message on the a screen:

![image](https://github.com/bigomics/omicsplayground/assets/85561624/01d5ca8d-226e-43e1-b25e-c6ce153cb04a)

Cell type profiling was on, so I believe it might have to do with the conversion of mouse IDs into human orthologues. Can you take a look please?

**Comment by mauromiguelm** [comment]
Hi Axel, which dataset? to save the computation, we allow the extra modules to crash.. the log file should have the reason to why it crashed.

If you send us the dataset / params.RData, it will be easier to debug
