### ISSUE TITLE
Modifications to the GO graph are not stored in the PNG/PDF output. PDF output is furthermore corrupted (v3.4.1-master240626)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#981]
Whenever I try to modify the GO term graph, by moving the boxes around I cannot save any of the changes in the pdf/png output:

![image](https://github.com/bigomics/omicsplayground/assets/85561624/a78cac0b-208a-418e-b4b2-132f895b446b)

Furthermore, whenever I try to save the ouput as a pdf file I get a corrupted file of 0b:

![image](https://github.com/bigomics/omicsplayground/assets/85561624/0a5bc14c-1261-458d-b5ae-c2f462ca10e7)

**Comment by ivokwee** [comment]
PDF download is working in v3.5.0-beta10. You can download the modified plot by right clicking on the graph and do "save image as..." (in Chrome). Closing issue.

![image](https://github.com/user-attachments/assets/58150984-c39f-4bc1-aec3-2809182cbdae)
