### ISSUE TITLE
Venn Diagramm issue in the "Compare Signature" tab

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#99]
When trying to separate DEGs in the Venn Diagramm produced by the "Compare Signature" tab  in version 2.8.5 of the platform, nothing happens. I should be getting separate numbers showing the number of up- and down-regulated genes.

![image](https://user-images.githubusercontent.com/85561624/159707699-7630e7f0-0363-44cd-9dc0-95df998b6ada.png)

**Comment by ivokwee** [comment]
Checked. It solved now.
