### ISSUE TITLE
Clustering tabs disappearing in chrome (v3.4.1-master240626)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#994]
This has also been reported by another user, but I noticed that when I load a random dataset into the platform, sometimes the clustering menu does not open and I have to reload the platform to get it working. 

The issue appears to be very random and I cannot recreate it with a specific dataset.

**Comment by profundity** [comment]
Same here.  Happens too often.

Also, there was a time course option.  Am I right.........cannot find it anymore.

**Comment by ESCRI11** [comment]
This was fixed here https://github.com/bigomics/omicsplayground/pull/986 ; soon to be deployed
